import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'hi' | 'bn' | 'te' | 'mr' | 'ta' | 'gu' | 'kn' | 'ml' | 'pa';

interface LanguageContextType {
  language: Language;
  locale: string;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const languages = [
  { id: 'en', label: 'English' },
  { id: 'hi', label: 'हिन्दी' },
  { id: 'bn', label: 'বাংলা' },
  { id: 'te', label: 'తెలుగు' },
  { id: 'mr', label: 'मराठी' },
  { id: 'ta', label: 'தமிழ்' },
  { id: 'gu', label: 'ગુજરાતી' },
  { id: 'kn', label: 'ಕನ್ನಡ' },
  { id: 'ml', label: 'മലയാളം' },
  { id: 'pa', label: 'ਪੰਜਾਬੀ' },
];

const translations = {
  en: {
    dashboard: 'Dashboard',
    overview: 'Overview',
    patients: 'Patients',
    messages: 'Secure Messages',
    profile: 'Profile',
    logout: 'Logout',
    goodMorning: 'Good morning',
    goodAfternoon: 'Good afternoon',
    goodEvening: 'Good evening',
    welcomeBack: 'Welcome back',
    scheduledForToday: 'scheduled for today',
    casesRequireAttention: 'cases require immediate clinical attention',
    allSystemsNormal: 'All systems are operating within normal parameters',
    simulateEmergency: 'Simulate Emergency',
    todayAppointments: 'Today appointments',
    criticalCases: 'Critical Cases',
    actionRequired: 'Action required',
    inPipeline: 'In pipeline',
    scheduled: 'Scheduled',
    priorityQueue: 'Priority Patient Queue',
    automatedSorting: 'Automated severity sorting active',
    newAdmission: 'New Admission',
    noPendingCases: 'No pending high-priority cases',
    waitingForSignals: 'Waiting for diagnostic signals',
    analyze: 'Analyze',
    totalActivePatients: 'Total Active Patients',
    avgConsultations: 'Avg. Consultations / Mo',
    diagnosticAccuracy: 'Diagnostic Accuracy',
    patientSatisfaction: 'Patient Satisfaction',
    patientDirectory: 'Patient Directory',
    syncRegistry: 'Synchronize Clinical Registry',
    activeCases: 'Active Medical Cases',
    searchPatientsList: 'Search by name or clinical status...',
    noPatientsFound: 'No patients matching your search criteria.',
    addPatient: 'Add Patient',
    registryOf: 'Registry of',
    assignedSubjects: 'assigned subjects by Clinical Admin',
    syncAdminAssignments: 'Synchronize Admin Assignments',
    dr: 'Dr.',
    searchPatients: 'Search patient database...',
    activePatients: 'Active Patients',
    criticalAlerts: 'Critical Alerts',
    pendingReviews: 'Pending Reviews',
    clinicalExcellence: 'Clinical Excellence',
    recentActivity: 'Recent Clinical Activity',
    emergency: 'Emergency',
    critical: 'Critical',
    normal: 'Normal',
    confirmed: 'Confirmed',
    pending: 'Pending',
    activePractice: 'Active Practice',
    experience: 'Experience',
    totalProcedures: 'Total Procedures',
    education: 'Education',
    certifications: 'Certifications',
    professionalBiography: 'Professional Biography',
    workplaceInfo: 'Workplace Info',
    weeklyPatientVolume: 'Weekly Patient Volume',
    diagnosticReports: 'Diagnostic Reports',
    pharmacy: 'Pharmacy',
    scheduling: 'Scheduling',
    secureConsult: 'Secure Consult',
    clinicalNotes: 'Clinical Notes',
    consultations: 'Consultations',
    activeLink: 'Secure Active Link',
    typeMessage: 'Type clinical response...',
    aryanKumar: 'Aryan Kumar',
    elenaGilbert: 'Elena Gilbert',
    stefanSalvatore: 'Stefan Salvatore',
    damonSalvatore: 'Damon Salvatore',
    bonnieBennett: 'Bonnie Bennett',
    janeDoe: 'Jane Doe',
    emergencyCases: 'Emergency Cases',
    normalCases: 'Normal Cases',
    activeCasesUnderCare: 'Active cases under your care',
    generating: 'Generating...',
    automateNote: 'Smart Scribe',
    bloodType: 'Blood Type',
    lastVisit: 'Last Visit',
    mockBloodType: 'O Positive',
    noPatientsAssigned: 'No Patients Assigned',
    noSubjectsAssigned: 'You currently have no subjects designated to your care by the administration. Use the synchronize button to retrieve your caseload.',
    electronicHealthRecord: 'Electronic Health Record',
    demographics: 'Demographics',
    contactLabel: 'Contact',
    familyGuardian: 'Family Guardian',
    biometrics: 'Biometrics',
    heartRate: 'Heart Rate',
    bloodPressure: 'Blood Pressure',
    clinicalProgressNotes: 'Clinical Progress Notes',
    formalMedicalRecords: 'Formal medical records',
    addDiagnosis: 'Add Diagnosis',
    collapse: 'Collapse',
    primaryImpression: 'Primary Impression',
    clinicalObservationDetails: 'Clinical Observation Details',
    commitToDataRegistry: 'Commit to Data Registry',
    assessmentRecord: 'Assessment Record',
    verifiedByMedicalStaff: 'Verified by Medical Staff',
    exportRecord: 'Export Record',
    noFormalRecords: 'No formal clinical records found.',
    activePrescriptions: 'Active Prescriptions',
    currentMedicationRegimen: 'Current medication regimen',
    newPrescription: 'New Prescription',
    medication: 'Medication',
    dosage: 'Dosage',
    duration: 'Duration',
    issuePrescription: 'Issue Prescription',
    renew: 'Renew',
    noActivePrescriptions: 'No active prescriptions found.',
    laboratoryResults: 'Laboratory Results',
    recentDiagnosticMetrics: 'Recent diagnostic metrics',
    newLabOrder: 'New Lab Order',
    testType: 'Test Type',
    submitOrder: 'Submit Order',
    noLabResults: 'No laboratory results found.',
    upcomingAppointments: 'Upcoming Appointments',
    scheduledConsultations: 'Scheduled consultations',
    noUpcomingAppointments: 'No upcoming appointments found.',
    hypertensionStage1: 'Hypertension Stage 1',
    hypertensionNotes: 'Systemic evaluation shows consistent elevated readings. Initiating lifestyle modification protocol.',
    seasonalAllergies: 'Seasonal Allergies',
    allergiesNotes: 'Patient reports persistent rhinitis and ocular pruritus during spring cycles.',
    lisinopril: 'Lisinopril',
    loratadine: 'Loratadine',
    thirtyDays: '30 Days',
    asNeeded: 'As needed',
    lipidPanel: 'Lipid Panel',
    metabolicScreening: 'Metabolic Screening',
    completedStatus: 'Completed',
    orderedStatus: 'Ordered',
    cancel: 'Cancel',
    totalCholesterol: 'Total Cholesterol',
    abnormalStatus: 'Abnormal',
    fastingGlucose: 'Fasting Glucose',
    followUpConsultation: 'Follow-up consultation',
  },
  hi: {
    dashboard: 'डैशबोर्ड',
    overview: 'अवलोकन',
    patients: 'मरीज',
    messages: 'सुरक्षित संदेश',
    profile: 'प्रोफ़ाइल',
    logout: 'लॉगआउट',
    goodMorning: 'शुभ प्रभात',
    goodAfternoon: 'शुभ दोपहर',
    goodEvening: 'शुभ संध्या',
    welcomeBack: 'वापसी पर स्वागत है',
    scheduledForToday: 'आज के लिए निर्धारित',
    casesRequireAttention: 'मामलों पर तत्काल नैदानिक ध्यान देने की आवश्यकता है',
    allSystemsNormal: 'सभी प्रणालियाँ सामान्य मानकों के भीतर चल रही हैं',
    simulateEmergency: 'आपातकाल का अनुकरण करें',
    todayAppointments: 'आज की नियुक्तियां',
    criticalCases: 'गंभीर मामले',
    actionRequired: 'कार्रवाई आवश्यक',
    inPipeline: 'पाइपलाइन में',
    scheduled: 'निर्धारित',
    priorityQueue: 'प्राथमिकता मरीज कतार',
    automatedSorting: 'स्वचालित गंभीरता वर्गीकरण सक्रिय',
    newAdmission: 'नया प्रवेश',
    noPendingCases: 'कोई लंबित उच्च-प्राथमिकता मामले नहीं',
    waitingForSignals: 'नैदानिक संकेतों की प्रतीक्षा है',
    analyze: 'विश्लेषण करें',
    totalActivePatients: 'कुल सक्रिय मरीज',
    avgConsultations: 'औसत परामर्श / माह',
    diagnosticAccuracy: 'नैदानिक सटीकता',
    patientSatisfaction: 'मरीज संतुष्टि',
    patientDirectory: 'मरीज निर्देशिका',
    syncRegistry: 'नैदानिक रजिस्ट्री को सिंक्रोनाइज़ करें',
    activeCases: 'सक्रिय चिकित्सा मामले',
    searchPatientsList: 'नाम या नैदानिक स्थिति से खोजें...',
    noPatientsFound: 'आपकी खोज के मानदंडों से मेल खाने वाला कोई मरीज नहीं मिला.',
    addPatient: 'मरीज जोड़ें',
    registryOf: 'रजिस्ट्री',
    assignedSubjects: 'मरीजों की नैदानिक व्यवस्था द्वारा',
    syncAdminAssignments: 'व्यवस्था कार्यभार सिंक्रोनाइज़ करें',
    dr: 'डॉ.',
    searchPatients: 'मरीज डेटाबेस खोजें...',
    activePatients: 'सक्रिय मरीज',
    criticalAlerts: 'गंभीर अलर्ट',
    pendingReviews: 'लंबित समीक्षाएं',
    clinicalExcellence: 'नैदानिक उत्कृष्टता',
    recentActivity: 'हाल की नैदानिक गतिविधि',
    emergency: 'आपातकालीन',
    critical: 'गंभीर',
    normal: 'सामान्य',
    confirmed: 'पुष्टि की गई',
    pending: 'लंबित',
    activePractice: 'सक्रिय अभ्यास',
    experience: 'अनुभव',
    totalProcedures: 'कुल प्रक्रियाएं',
    education: 'शिक्षा',
    certifications: 'प्रमाणपत्र',
    professionalBiography: 'पेशेवर जीवनी',
    workplaceInfo: 'कार्यस्थल की जानकारी',
    weeklyPatientVolume: 'साप्ताहिक मरीज संख्या',
    diagnosticReports: 'नैदानिक रिपोर्ट',
    pharmacy: 'फार्मेसी',
    scheduling: 'अनुसूचन',
    secureConsult: 'सुरक्षित परामर्श',
    clinicalNotes: 'नैदानिक नोट्स',
    consultations: 'परामर्श',
    activeLink: 'सुरक्षित सक्रिय लिंक',
    typeMessage: 'नैदानिक प्रतिक्रिया लिखें...',
    aryanKumar: 'आर्यन कुमार',
    elenaGilbert: 'एलेना गिल्बर्ट',
    stefanSalvatore: 'स्टीफन साल्वाटोर',
    damonSalvatore: 'डेमन साल्वाटोर',
    bonnieBennett: 'बोनी बेनेट',
    janeDoe: 'जेन डो',
    emergencyCases: 'आपातकालीन मामले',
    normalCases: 'सामान्य मामले',
    activeCasesUnderCare: 'आपकी देखभाल में सक्रिय मामले',
    generating: 'तैयार कर रहा है...',
    automateNote: 'स्मार्ट स्क्राइब',
    bloodType: 'रक्त प्रकार',
    lastVisit: 'अंतिम उपस्थिति',
    mockBloodType: 'ओ पॉजिटिव',
    noPatientsAssigned: 'कोई मरीज सौंपा नहीं गया',
    noSubjectsAssigned: 'प्रशासन द्वारा आपको कोई मरीज नहीं दिया गया है। अपनी कतार प्राप्त करने के लिए सिंक्रोनाइज़ बटन का उपयोग करें।',
    electronicHealthRecord: 'इलेक्ट्रॉनिक स्वास्थ्य रिकॉर्ड',
    demographics: 'जनसांख्यिकी',
    contactLabel: 'संपर्क',
    familyGuardian: 'पारिवारिक अभिभावक',
    biometrics: 'बायोमेट्रिक्स',
    heartRate: 'हृदय गति',
    bloodPressure: 'रक्तचाप',
    clinicalProgressNotes: 'नैदानिक प्रगति नोट्स',
    formalMedicalRecords: 'औपचारिक चिकित्सा रिकॉर्ड',
    addDiagnosis: 'निदान जोड़ें',
    collapse: 'संकोचन',
    primaryImpression: 'प्राथमिक धारणा',
    clinicalObservationDetails: 'नैदानिक अवलोकन विवरण',
    commitToDataRegistry: 'डेटा रजिस्ट्री में सहेजें',
    assessmentRecord: 'मूल्यांकन रिकॉर्ड',
    verifiedByMedicalStaff: 'चिकित्सा कर्मचारियों द्वारा सत्यापित',
    exportRecord: 'रिकॉर्ड निर्यात करें',
    noFormalRecords: 'कोई औपचारिक नैदानिक रिकॉर्ड नहीं मिला।',
    activePrescriptions: 'सक्रिय नुस्खे',
    currentMedicationRegimen: 'वर्तमान दवा व्यवस्था',
    newPrescription: 'नया पर्चा',
    medication: 'दवा',
    dosage: 'खुराक',
    duration: 'अवधि',
    issuePrescription: 'पर्चा जारी करें',
    renew: 'नवीनीकरण',
    noActivePrescriptions: 'कोई सक्रिय पर्ची नहीं मिली।',
    laboratoryResults: 'प्रयोगशाला परिणाम',
    recentDiagnosticMetrics: 'हालिया नैदानिक मेट्रिक्स',
    newLabOrder: 'नया लैब ऑर्डर',
    testType: 'परीक्षण प्रकार',
    submitOrder: 'ऑर्डर सबमिट करें',
    noLabResults: 'कोई प्रयोगशाला परिणाम नहीं मिला।',
    upcomingAppointments: 'आगामी नियुक्तियां',
    scheduledConsultations: 'निर्धारित परामर्श',
    noUpcomingAppointments: 'कोई आगामी नियुक्ति नहीं मिली।',
    hypertensionStage1: 'उच्च रक्तचाप चरण 1',
    hypertensionNotes: 'प्रणालीगत मूल्यांकन लगातार उन्नत रीडिंग दिखाता है। जीवन शैली संशोधन प्रोटोकॉल शुरू करना।',
    seasonalAllergies: 'मौसमी एलर्जी',
    allergiesNotes: 'मरीज ने वसंत ऋतु में लगातार राइनाइटिस और ओकुलर प्रुरिटस की सूचना दी है।',
    lisinopril: 'लाइसिनोप्रिल',
    loratadine: 'लोराटाडीन',
    thirtyDays: '30 दिन',
    asNeeded: 'जरूरत के अनुसार',
    lipidPanel: 'लिपिड पैनल',
    metabolicScreening: 'चयापचय स्क्रीनिंग',
    completedStatus: 'पूर्ण',
    orderedStatus: 'ऑर्डर किया गया',
    cancel: 'रद्द करें',
    totalCholesterol: 'कुल कोलेस्ट्रॉल',
    abnormalStatus: 'असामान्य',
    fastingGlucose: 'फास्टिंग ग्लूकोज',
    followUpConsultation: 'फॉलो-अप परामर्श',
  },
  bn: {
    dashboard: 'ড্যাশবোর্ড',
    overview: 'সংক্ষিপ্ত বিবরণ',
    patients: 'রোগী',
    messages: 'সুরক্ষিত বার্তা',
    profile: 'প্রোফাইল',
    logout: 'লগআউট',
    goodMorning: 'সুপ্রভাত',
    goodAfternoon: 'শুভ অপরাহ্ন',
    goodEvening: 'শুভ সন্ধ্যা',
    welcomeBack: 'স্বাগতম',
    allSystemsNormal: 'সমস্ত সিস্টেম স্বাভাবিক',
    simulateEmergency: 'জরুরী অনুকরণ করুন',
    todayAppointments: 'আজকের অ্যাপয়েন্টমেন্ট',
    criticalCases: 'গুরুতর কেস',
    actionRequired: 'পদক্ষেপ প্রয়োজন',
    inPipeline: 'পাইপলাইনে',
    scheduled: 'নির্ধারিত',
    priorityQueue: 'অগ্রাধিকার রোগী সারি',
    automatedSorting: 'স্বয়ংক্রিয় তীব্রতা বাছাই সক্রিয়',
    newAdmission: 'নতুন ভর্তি',
    noPendingCases: 'কোনো অপেক্ষমাণ উচ্চ-অগ্রাধিকার কেস নেই',
    waitingForSignals: 'ডায়াগনস্টিক সিগন্যালের জন্য অপেক্ষা করা হচ্ছে',
    analyze: 'বিশ্লেষণ করুন',
    totalActivePatients: 'মোট সক্রিয় রোগী',
    avgConsultations: 'গড় পরামর্শ / মাস',
    diagnosticAccuracy: 'ডায়াগনস্টিক নির্ভুলতা',
    patientSatisfaction: 'রোগীর সন্তুষ্টি',
    patientDirectory: 'রোগী ডিরেক্টরি',
    syncRegistry: 'ক্লিনিক্যাল রেজিস্ট্রি সিঙ্ক করুন',
    activeCases: 'সক্রিয় মেডিকেল কেস',
    searchPatientsList: 'নাম বা ক্লিনিক্যাল স্ট্যাটাস দিয়ে খুঁজুন...',
    noPatientsFound: 'কোনো রোগী পাওয়া যায়নি.',
    addPatient: 'রোগী যোগ করুন',
    registryOf: 'এর রেজিস্ট্রি',
    assignedSubjects: 'ক্লিনিক্যাল অ্যাডমিন দ্বারা নির্ধারিত বিষয়',
    syncAdminAssignments: 'অ্যাডমিন অ্যাসাইনমেন্ট সিঙ্ক করুন',
    dr: 'ডা.',
    searchPatients: 'রোগী অনুসন্ধান করুন...',
    activePatients: 'সক্রিয় রোগী',
    criticalAlerts: 'গুরুতর সতর্কতা',
    pendingReviews: 'অপেক্ষমাণ পর্যালোচনা',
    clinicalExcellence: 'ক্লিনিক্যাল শ্রেষ্ঠত্ব',
    recentActivity: 'সাম্প্রতিক ক্লিনিক্যাল কার্যকলাপ',
    emergency: 'জরুরী অবস্থা',
    critical: 'গুরুতর',
    normal: 'স্বাভাবিক',
    confirmed: 'নিশ্চিত',
    pending: 'অপেক্ষমাণ',
    activePractice: 'সক্রিয় অনুশীলন',
    experience: 'অভিজ্ঞতা',
    totalProcedures: 'মোট প্রক্রিয়া',
    education: 'শিক্ষা',
    certifications: 'সার্টিফিকেশন',
    professionalBiography: 'পেশাগত জীবনী',
    workplaceInfo: 'কর্মক্ষেত্রের তথ্য',
    weeklyPatientVolume: 'সাপ্তাহিক রোগীর সংখ্যা',
    diagnosticReports: 'ডায়াগনস্টিক রিপোর্ট',
    pharmacy: 'ফার্মেসি',
    scheduling: 'সময়সূচী',
    secureConsult: 'সুরক্ষিত পরামর্শ',
    clinicalNotes: 'ক্লিনিক্যাল নোট',
    consultations: 'পরামর্শ',
    activeLink: 'সুরক্ষিত সক্রিয় লিঙ্ক',
    typeMessage: 'ক্লিনিক্যাল প্রতিক্রিয়া লিখুন...',
    emergencyCases: 'জরুরী কেস',
    normalCases: 'সাধারণ কেস',
    activeCasesUnderCare: 'আপনার তত্ত্বাবধানে সক্রিয় কেসগুলি',
    generating: 'তৈরি হচ্ছে...',
    automateNote: 'স্মার্ট সাবলীল',
    aryanKumar: 'আরিয়ান কুমার',
    elenaGilbert: 'এলিনা গিলবার্ট',
    stefanSalvatore: 'স্টেফান সালভাটোর',
    damonSalvatore: 'ডেমন সালভাটোর',
    bonnieBennett: 'বনি বেনেট',
    janeDoe: 'জেন ডো',
    bloodType: 'রক্তের গ্রুপ',
    lastVisit: 'শেষ পরিদর্শন',
    mockBloodType: 'ও পজিটিভ',
    noPatientsAssigned: 'কোনও রোগী বরাদ্দ করা হয়নি',
    noSubjectsAssigned: 'প্রশাসন দ্বারা আপনাকে বর্তমানে কোনও রোগী দেওয়া হয়নি। আপনার কেসলোড পেতে সিঙ্ক্রোনাইজ বোতামটি ব্যবহার করুন।',
    electronicHealthRecord: 'ইলেকট্রনিক স্বাস্থ্য রেকর্ড',
    demographics: 'জনমিতি',
    contactLabel: 'যোগাযোগ',
    familyGuardian: 'পারিবারিক অভিভাবক',
    biometrics: 'বায়োমেট্রিক্স',
    heartRate: 'হৃদস্পন্দন',
    bloodPressure: 'রক্তচাপ',
    clinicalProgressNotes: 'ক্লিনিক্যাল অগ্রগতি নোট',
    formalMedicalRecords: 'আনুষ্ঠানিক মেডিকেল রেকর্ড',
    addDiagnosis: 'রোগ নির্ণয় যোগ করুন',
    collapse: 'সংকুচিত করুন',
    primaryImpression: 'প্রাথমিক ধারণা',
    clinicalObservationDetails: 'ক্লিনিক্যাল পর্যবেক্ষণ বিবরণ',
    commitToDataRegistry: 'ডেটা রেজিস্ট্রিতে সংরক্ষণ করুন',
    assessmentRecord: 'মূল্যায়ন রেকর্ড',
    verifiedByMedicalStaff: 'চিকিৎসা কর্মীদের দ্বারা যাচাইকৃত',
    exportRecord: 'রেকর্ড রপ্তানি করুন',
    noFormalRecords: 'কোনও আনুষ্ঠানিক ক্লিনিক্যাল রেকর্ড পাওয়া যায়নি।',
    activePrescriptions: 'সক্রিয় প্রেসক্রিপশন',
    currentMedicationRegimen: 'বর্তমান ঔষধ নিয়মಾವলী',
    newPrescription: 'নতুন প্রেসক্রিপশন',
    medication: 'ওষুধ',
    dosage: 'ডোজ',
    duration: 'সময়কাল',
    issuePrescription: 'প্রেসক্রিপশন প্রদান করুন',
    renew: 'পুনর্নবীকরণ',
    noActivePrescriptions: 'কোনও সক্রিয় প্রেসক্রিপশন পাওয়া যায়নি।',
    laboratoryResults: 'ল্যাবরেটরির ফলাফল',
    recentDiagnosticMetrics: 'সাম্প্রতিক ডায়াগনস্টিক মেট্রিক্স',
    newLabOrder: 'নতুন ল্যাব অর্ডার',
    testType: 'টেস্টের ধরন',
    submitOrder: 'অর্ডার জমা দিন',
    noLabResults: 'কোনও ল্যাবরেটরির ফলাফল পাওয়া যায়নি।',
    upcomingAppointments: 'আসন্ন অ্যাপয়েন্টমেন্ট',
    scheduledConsultations: 'নির্ধারিত পরামর্শ',
    noUpcomingAppointments: 'কোনও আসন্ন অ্যাপয়েন্টমেন্ট পাওয়া যায়নি।',
    hypertensionStage1: 'উচ্চ রক্তচাপ পর্যায় 1',
    hypertensionNotes: 'পদ্ধতিগত মূল্যায়নে ক্রমাগতভাবে রিডিং বেশি দেখাচ্ছে। জীবনধারা পরিবর্তনের প্রোটোকল শুরু করছি।',
    seasonalAllergies: 'মৌসুমি অ্যালার্জি',
    allergiesNotes: 'রোগী বসন্ত চক্রে অবিরাম রাইনাইটিস এবং অকুলার প্রুরিটাসের অভিযোগ করেছেন।',
    lisinopril: 'লিসিনোপ্রিল',
    loratadine: 'লোরাটাডিন',
    thirtyDays: '৩০ দিন',
    asNeeded: 'প্রয়োজন অনুযায়ী',
    lipidPanel: 'লিপিড প্যানেল',
    metabolicScreening: 'মেটাবলিক স্ক্রীনিং',
    completedStatus: 'সম্পন্ন',
    orderedStatus: 'অর্ডার করা হয়েছে',
    cancel: 'বাতিল করুন',
    totalCholesterol: 'মোট কোলেস্টেরল',
    abnormalStatus: 'অস্বাভাবিক',
    fastingGlucose: 'ফাস্টিং গ্লুকোজ',
    followUpConsultation: 'ফলো-আপ পরামর্শ',
  },
  te: {
    dashboard: 'డాష్‌బోర్డ్',
    overview: 'అవలోకనం',
    patients: 'రోగులు',
    messages: 'సురక్షిత సందేశాలు',
    profile: 'ప్రొఫైల్',
    logout: 'లాగ్అవుట్',
    goodMorning: 'శుభోదయం',
    goodAfternoon: 'శుభాహ్నం',
    goodEvening: 'శుభ సాయంత్రం',
    welcomeBack: 'స్వాగతం',
    allSystemsNormal: 'అన్ని సిస్టమ్స్ సాధారణం',
    simulateEmergency: 'అత్యవసర పరిస్థితిని అనుకరించండి',
    todayAppointments: 'నేటి అపాయింట్‌మెంట్‌లు',
    criticalCases: 'క్లిష్టమైన కేసులు',
    actionRequired: 'చర్య అవసరం',
    inPipeline: 'పైప్‌లైన్‌లో',
    scheduled: 'షెడ్యూల్ చేయబడింది',
    priorityQueue: 'ప్రాధాన్యతా రోగి క్యూ',
    automatedSorting: 'ఆటోమేటెడ్ తీవ్రత క్రమబద్ధీకరణ సక్రియం',
    newAdmission: 'కొత్త ప్రవేశం',
    noPendingCases: 'పెండింగ్‌లో ఉన్న అధిక-ప్రాధాన్యత కేసులు లేవు',
    waitingForSignals: 'డయాగ్నస్టిక్ సిగ్నల్స్ కోసం వేచి ఉంది',
    analyze: 'విశ్లేషించండి',
    totalActivePatients: 'మొత్తం క్రియాశీల రోగులు',
    avgConsultations: 'సగటు సంప్రదింపులు / నెలకు',
    diagnosticAccuracy: 'రోగ నిర్ధారణ ఖచ్చితత్వం',
    patientSatisfaction: 'రోగి సంతృప్తి',
    patientDirectory: 'రోగి డైరెక్టరీ',
    syncRegistry: 'క్లినికల్ రిజిస్ట్రీని సమకాలీకరించండి',
    activeCases: 'క్రియాశీల వైద్య కేసులు',
    searchPatientsList: 'పేరు లేదా క్లినికల్ స్థితి ద్వారా శోధించండి...',
    noPatientsFound: 'మీ శోధనకు తగిన రోగులు కనుగొనబడలేదు.',
    addPatient: 'రోగిని జోడించండి',
    registryOf: 'రిజిస్ట్రీ',
    assignedSubjects: 'క్లినికల్ అడ్మిన్ ద్వారా కేటాయించబడిన రోగులు',
    syncAdminAssignments: 'అడ్మిన్ కేటాయింపులను సమకాలీకరించండి',
    dr: 'డాక్టర్.',
    searchPatients: 'రోగుల కోసం వెతకండి...',
    activePatients: 'సక్రియ రోగులు',
    criticalAlerts: 'క్లిష్టమైన హెచ్చరికలు',
    pendingReviews: 'పెండింగ్ సమీక్షలు',
    clinicalExcellence: 'క్లినికల్ ఎక్సలెన్స్',
    recentActivity: 'ఇటీవలి క్లినికల్ కార్యాచరణ',
    emergency: 'అత్యవసర పరిస్థితి',
    critical: 'క్లిష్టమైన',
    normal: 'సాధారణ',
    confirmed: 'నిర్ధారించబడింది',
    pending: 'పెండింగ్‌లో ఉంది',
    activePractice: 'క్రియాశీల అభ్యాసం',
    experience: 'అనుభవం',
    totalProcedures: 'మొత్తం విధానాలు',
    education: 'విద్య',
    certifications: 'ధృవపత్రాలు',
    professionalBiography: 'వృత్తిపరమైన జీవిత చరిత్ర',
    workplaceInfo: 'కార్యాలయం సమాచారం',
    weeklyPatientVolume: 'వారపు రోగి పరిమాణం',
    diagnosticReports: 'డయాగ్నస్టిక్ నివేదికలు',
    pharmacy: 'ఫార్మసీ',
    scheduling: 'షెడ్యూలింగ్',
    secureConsult: 'సురక్షిత సంప్రదింపు',
    clinicalNotes: 'క్లినికల్ నోట్స్',
    consultations: 'సంప్రదింపులు',
    activeLink: 'సురక్షిత క్రియాశీల లింక్',
    typeMessage: 'క్లినికల్ ప్రతిస్పందనను టైప్ చేయండి...',
    aryanKumar: 'ఆర్యన్ కుమార్',
    elenaGilbert: 'ఎలెనా గిల్బర్ట్',
    stefanSalvatore: 'స్టీఫన్ సాల్వాటోర్',
    damonSalvatore: 'డామన్ సాల్వాటోర్',
    bonnieBennett: 'బోనీ బెన్నెట్',
    janeDoe: 'జేన్ డో',
    emergencyCases: 'అత్యవసర కేసులు',
    normalCases: 'సాధారణ కేసులు',
    activeCasesUnderCare: 'మీ సంరక్షణలో క్రియాశీల కేసులు',
    generating: 'సృష్టిస్తోంది...',
    automateNote: 'స్మార్ట్ సబ్',
    bloodType: 'రక్త వర్గం',
    lastVisit: 'చివరి సందర్శన',
    mockBloodType: 'ఓ పాజిటివ్',
    noPatientsAssigned: 'రోగులు కేటాయించబడలేదు',
    noSubjectsAssigned: 'ప్రస్తుతం మీ సంరక్షణ కోసం పరిపాలన ద్వారా ఎవరూ కేటాయించబడలేదు. మీ జాబితాను పొందడానికి సింక్రొనైజ్ బటన్‌ను ఉపయోగించండి.',
    electronicHealthRecord: 'ఎలక్ట్రానిక్ హెల్త్ రికార్డ్',
    demographics: 'జనాభా వివరాలు',
    contactLabel: 'సంప్రదింపు',
    familyGuardian: 'కుటుంబ సంరక్షకుడు',
    biometrics: 'బయోమెట్రిక్స్',
    heartRate: 'హృదయ స్పందన రేటు',
    bloodPressure: 'రక్తపోటు',
    clinicalProgressNotes: 'క్లినికల్ ప్రోగ్రెస్ నోట్స్',
    formalMedicalRecords: 'అధికారిక వైద్య రికార్డులు',
    addDiagnosis: 'రోగ నిర్ధారణను జోడించండి',
    collapse: 'కుదించు',
    primaryImpression: 'ప్రాథమిక అభిప్రాయం',
    clinicalObservationDetails: 'క్లినికల్ పరిశీలన వివరాలు',
    commitToDataRegistry: 'డేటా రికార్డులో భద్రపరచు',
    assessmentRecord: 'అంచనా రికార్డ్',
    verifiedByMedicalStaff: 'వైద్య సిబ్బందిచే ధృవీకరించబడింది',
    exportRecord: 'రికార్డ్‌ను ఎగుమతి చేయండి',
    noFormalRecords: 'అధికారిక క్లినికల్ రికార్డులు కనుగొనబడలేదు.',
    activePrescriptions: 'యాక్టివ్ ప్రిస్క్రిప్షన్లు',
    currentMedicationRegimen: 'ప్రస్తుత ఔషధ విధానం',
    newPrescription: 'కొత్త ప్రిస్క్రిప్షన్',
    medication: 'ఔషధం',
    dosage: 'మోతాదు',
    duration: 'వ్యవధి',
    issuePrescription: 'ప్రిస్క్రిప్షన్ జారీ చేయండి',
    renew: 'పునరుద్ధరించండి',
    noActivePrescriptions: 'యాక్టివ్ ప్రిస్క్రిప్షన్లు ఏవీ కనుగొనబడలేదు.',
    laboratoryResults: 'ల్యాబ్ ఫలితాలు',
    recentDiagnosticMetrics: 'ఇటీవలి రోగనిర్ధారణ కొలమానాలు',
    newLabOrder: 'కొత్త ల్యాబ్ ఆర్డర్',
    testType: 'పరీక్ష రకం',
    submitOrder: 'ఆర్డర్ సమర్పించండి',
    noLabResults: 'ల్యాబ్ ఫలితాలు ఏవీ కనుగొనబడలేదు.',
    upcomingAppointments: 'రాబోయే అపాయింట్‌మెంట్‌లు',
    scheduledConsultations: 'షెడ్యూల్ చేసిన కన్సల్టేషన్లు',
    noUpcomingAppointments: 'రాబోయే అపాయింట్‌మెంట్‌లు ఏవీ కనుగొనబడలేదు.',
    hypertensionStage1: 'రక్తపోటు దశ 1',
    hypertensionNotes: 'సిస్టమిక్ మూల్యాంకనం స్థిరమైన అధిక రీడింగ్స్‌ను చూపుతుంది. జీవనశైలి మార్పు ప్రోటోకాల్‌ను ప్రారంభిస్తోంది.',
    seasonalAllergies: 'కాలానుగుణ అలెర్జీలు',
    allergiesNotes: 'స్ప్రింగ్ సైకిల్స్ (వసంత కాలం)లో రోగి నిరంతర నాసికా మరియు కళ్ల దురద ఉన్నట్లు నివేదించారు.',
    lisinopril: 'లిసినోప్రిల్',
    loratadine: 'లోరాటాడిన్',
    thirtyDays: '30 రోజులు',
    asNeeded: 'అవసరమైనప్పుడు',
    lipidPanel: 'లిపిడ్ ప్యానెల్',
    metabolicScreening: 'మెటబాలిక్ స్క్రీనింగ్',
    completedStatus: 'పూర్తయింది',
    orderedStatus: 'ఆర్డర్ చేయబడింది',
    cancel: 'రద్దు చేయండి',
    totalCholesterol: 'మొత్తం కొలెస్ట్రాల్',
    abnormalStatus: 'అసాధారణ',
    fastingGlucose: 'ఉపవాస గ్లూకోజ్',
    followUpConsultation: 'ఫాలో-అప్ కన్సల్టేషన్',
  },
  mr: {
    dashboard: 'डॅशबोर्ड',
    overview: 'आढावा',
    patients: 'रुग्ण',
    messages: 'सुरक्षित संदेश',
    profile: 'प्रोफाइल',
    logout: 'लॉगआउट',
    goodMorning: 'शुभ सकाळ',
    goodAfternoon: 'शुभ दुपार',
    goodEvening: 'शुभ संध्याकाळ',
    welcomeBack: 'स्वागत आहे',
    allSystemsNormal: 'सर्व प्रणाल्या सामान्य आहेत',
    simulateEmergency: 'आणीबाणीचे अनुकरण करा',
    todayAppointments: 'आजच्या भेटी',
    criticalCases: 'गंभीर प्रकरणे',
    actionRequired: 'कृती आवश्यक',
    inPipeline: 'पाइपलाइनमध्ये',
    scheduled: 'नियोजित',
    priorityQueue: 'प्राधान्य रुग्ण रांग',
    automatedSorting: 'स्वयंचलित तीव्रता क्रमवारी सक्रिय',
    newAdmission: 'नवीन प्रवेश',
    noPendingCases: 'कोणतीही प्रलंबित उच्च-प्राधान्य प्रकरणे नाहीत',
    waitingForSignals: 'निदान संकेतांची प्रतीक्षा करत आहे',
    analyze: 'विश्लेषण करा',
    totalActivePatients: 'एकूण सक्रिय रुग्ण',
    avgConsultations: 'सरासरी सल्लामसलत / महिना',
    diagnosticAccuracy: 'निदान अचूकता',
    patientSatisfaction: 'रुग्णांचे समाधान',
    patientDirectory: 'रुग्ण निर्देशिका',
    syncRegistry: 'क्लिनिकल रेजिस्ट्री सिंक करा',
    activeCases: 'सक्रिय वैद्यकीय प्रकरणे',
    searchPatientsList: 'नाव किंवा वैद्यकीय स्थितीनुसार शोधा...',
    noPatientsFound: 'तुमच्या शोधाशी जुळणारे कोणतेही रुग्ण आढळले नाहीत.',
    addPatient: 'रुग्ण जोडा',
    registryOf: 'नोंदणी',
    assignedSubjects: 'क्लिनिकल प्रशासकाद्वारे नियुक्त केलेले विषय',
    syncAdminAssignments: 'प्रशासक असाइनमेंट सिंक करा',
    dr: 'डॉ.',
    searchPatients: 'रुग्ण शोधा...',
    activePatients: 'सक्रिय रुग्ण',
    criticalAlerts: 'गंभीर सूचना',
    pendingReviews: 'प्रलंबित पुनरावलोकने',
    clinicalExcellence: 'क्लिनिकल उत्कृष्टता',
    recentActivity: 'अलीकडील क्लिनिकल क्रियाकलाप',
    emergency: 'आणीबाणी',
    critical: 'गंभीर',
    normal: 'सामान्य',
    confirmed: 'पुष्टी केली',
    pending: 'प्रलंबित',
    activePractice: 'सक्रिय सराव',
    experience: 'अनुभव',
    totalProcedures: 'एकूण प्रक्रिया',
    education: 'शिक्षण',
    certifications: 'प्रमाणपत्रे',
    professionalBiography: 'व्यावसायिक चरित्र',
    workplaceInfo: 'कार्यस्थळाची माहिती',
    weeklyPatientVolume: 'साप्ताहिक रुग्ण संख्या',
    diagnosticReports: 'निदान अहवाल',
    pharmacy: 'फार्मसी',
    scheduling: 'वेळापत्रक',
    secureConsult: 'सुरक्षित सल्लामसलत',
    clinicalNotes: 'क्लिनिकल नोट्स',
    consultations: 'सल्लामसलत',
    activeLink: 'सुरक्षित सक्रिय लिंक',
    typeMessage: 'क्लिनिकल प्रतिसाद टाइप करा...',
    aryanKumar: 'आर्यन कुमार',
    elenaGilbert: 'एलेना गिल्बर्ट',
    stefanSalvatore: 'स्टीफन साल्वाटोर',
    damonSalvatore: 'डॅमन साल्वाटोर',
    bonnieBennett: 'बॉनी बेनेट',
    janeDoe: 'जेन डो',
    emergencyCases: 'आणीबाणी प्रकरणे',
    normalCases: 'सामान्य प्रकरणे',
    activeCasesUnderCare: 'तुमच्या देखरेखीखाली सक्रिय प्रकरणे',
    generating: 'तयार करत आहे...',
    automateNote: 'स्मार्ट स्क्राइब',
    bloodType: 'रक्तगट',
    lastVisit: 'शेवटची भेट',
    mockBloodType: 'ओ पॉझिटिव्ह',
    noPatientsAssigned: 'कोणतेही रुग्ण नियुक्त केलेले नाहीत',
    noSubjectsAssigned: 'सध्या प्रशासनाकडून आपल्याकडे कोणीही रुग्ण सोपविलेले नाहीत. आपली यादी मिळविण्यासाठी सिंक्रोनाइझ बटण वापरा.',
    electronicHealthRecord: 'इलेक्ट्रॉनिक आरोग्य रेकॉर्ड',
    demographics: 'लोकसंख्याशास्त्र',
    contactLabel: 'संपर्क',
    familyGuardian: 'कौटुंबिक पालक',
    biometrics: 'बायोमेट्रिक्स',
    heartRate: 'हृदय गती',
    bloodPressure: 'रक्तदाब',
    clinicalProgressNotes: 'क्लिनिकल प्रगती नोट्स',
    formalMedicalRecords: 'औपचारिक वैद्यकीय नोंदी',
    addDiagnosis: 'निदान जोडा',
    collapse: 'संकुचित करा',
    primaryImpression: 'प्राथमिक प्रभाव',
    clinicalObservationDetails: 'क्लिनिकल निरीक्षण तपशील',
    commitToDataRegistry: 'डेटा रजिस्ट्रीमध्ये जतन करा',
    assessmentRecord: 'मूल्यांकन रेकॉर्ड',
    verifiedByMedicalStaff: 'वैद्यकीय कर्मचाऱ्यांनी सत्यापित',
    exportRecord: 'रेकॉर्ड निर्यात करा',
    noFormalRecords: 'कोणतेही औपचारिक क्लिनिकल रेकॉर्ड आढळले नाही.',
    activePrescriptions: 'सक्रिय प्रिस्क्रिप्शन',
    currentMedicationRegimen: 'सध्याची औषध योजना',
    newPrescription: 'नवीन प्रिस्क्रिप्शन',
    medication: 'औषध',
    dosage: 'डोस',
    duration: 'कालावधी',
    issuePrescription: 'प्रिस्क्रिप्शन द्या',
    renew: 'नूतनीकरण करा',
    noActivePrescriptions: 'कोणतेही सक्रिय प्रिस्क्रिप्शन आढळले नाही.',
    laboratoryResults: 'प्रयोगशाळेचा निकाल',
    recentDiagnosticMetrics: 'अलीकडील निदान मेट्रिक्स',
    newLabOrder: 'नवीन लॅब ऑर्डर',
    testType: 'चाचणी प्रकार',
    submitOrder: 'ऑर्डर सबमिट करा',
    noLabResults: 'कोणतेही प्रयोगशाळा निकाल आढळले नाहीत.',
    upcomingAppointments: 'आगामी भेटी',
    scheduledConsultations: 'नियोजित सल्लामसलत',
    noUpcomingAppointments: 'कोणत्याही आगामी भेटी आढळल्या नाहीत.',
    hypertensionStage1: 'उच्च रक्तदाब टप्पा 1',
    hypertensionNotes: 'प्रणालीगत मूल्यांकनात सातत्याने वाढलेले रीडिंग दिसून येते. जीवनशैली सुधारणा प्रोटोकॉल सुरू करत आहे.',
    seasonalAllergies: 'हंगामी ऍलर्जी',
    allergiesNotes: 'रुग्णाने वसंत ऋतूमध्ये सतत नाकाचा आणि डोळ्यांचा त्रास नोंदवला आहे.',
    lisinopril: 'लिसिनोप्रिल',
    loratadine: 'लोराटाडाइन',
    thirtyDays: '30 दिवस',
    asNeeded: 'गरजेनुसार',
    lipidPanel: 'लिपिड पॅनेल',
    metabolicScreening: 'मेटाबॉलिक स्क्रीनिंग',
    completedStatus: 'पूर्ण',
    orderedStatus: 'ऑर्डर केले',
    cancel: 'रद्द करा',
    totalCholesterol: 'एकूण कोलेस्ट्रॉल',
    abnormalStatus: 'असामान्य',
    fastingGlucose: 'फास्टिंग ग्लुकोज',
    followUpConsultation: 'फॉलो-अप सल्लामसलत',
  },
  ta: {
    dashboard: 'டாஷ்போர்டு',
    overview: 'மேலோட்டம்',
    patients: 'நோயாளிகள்',
    messages: 'பாதுகாப்பான செய்திகள்',
    profile: 'சுயவிவரம்',
    logout: 'வெளியேறு',
    goodMorning: 'காலை வணக்கம்',
    goodAfternoon: 'மதிய வணக்கம்',
    goodEvening: 'மாலை வணக்கம்',
    welcomeBack: 'நல்வரவு',
    allSystemsNormal: 'அனைத்து அமைப்புகளும் இயல்பாக உள்ளன',
    simulateEmergency: 'அவசர நிலையை உருவகப்படுத்து',
    todayAppointments: 'இன்றைய சந்திப்புகள்',
    criticalCases: 'முக்கியமான வழக்குகள்',
    actionRequired: 'நடவடிக்கை தேவை',
    inPipeline: 'பைப்லைனில்',
    scheduled: 'திட்டமிடப்பட்டுள்ளது',
    priorityQueue: 'முன்னுரிமை நோயாளி வரிசை',
    automatedSorting: 'தானியங்கி தீவிர வரிசையாக்கம் செயலில் உள்ளது',
    newAdmission: 'புதிய சேர்க்கை',
    noPendingCases: 'நிலுவையில் உள்ள உயர் முன்னுரிமை வழக்குகள் இல்லை',
    waitingForSignals: 'கண்டறியும் சமிக்ஞைகளுக்காக காத்திருக்கிறது',
    analyze: 'பகுப்பாய்வு செய்',
    totalActivePatients: 'மொத்த செயலில் உள்ள நோயாளிகள்',
    avgConsultations: 'சராசரி ஆலோசனைகள் / மாதம்',
    diagnosticAccuracy: 'கண்டறியும் துல்லியம்',
    patientSatisfaction: 'நோயாளி திருப்தி',
    patientDirectory: 'நோயாளி கோப்பகம்',
    syncRegistry: 'மருத்துவ பதிவகத்தை ஒத்திசைக்கவும்',
    activeCases: 'செயலில் உள்ள மருத்துவ வழக்குகள்',
    searchPatientsList: 'பெயர் அல்லது மருத்துவ நிலை மூலம் தேடு...',
    noPatientsFound: 'உங்கள் தேடலுடன் பொருந்தும் நோயாளிகள் இல்லை.',
    addPatient: 'நோயாளியைச் சேர்',
    registryOf: 'பதிவகம்',
    assignedSubjects: 'மருத்துவ நிர்வாகியால் ஒதுக்கப்பட்ட நோயாளிகள்',
    syncAdminAssignments: 'நிர்வாகி பணிகளை ஒத்திசைக்கவும்',
    dr: 'டாக்டர்.',
    searchPatients: 'நோயாளிகளைத் தேடுங்கள்...',
    activePatients: 'செயலில் உள்ள நோயாளிகள்',
    criticalAlerts: 'முக்கியமான எச்சரிக்கைகள்',
    pendingReviews: 'நிலுவையில் உள்ள மதிப்பாய்வுகள்',
    clinicalExcellence: 'மருத்துவ சிறப்பம்சம்',
    recentActivity: 'சமீபத்திய மருத்துவ செயல்பாடு',
    emergency: 'அவசரநிலை',
    critical: 'மிக முக்கியம்',
    normal: 'இயல்பான',
    confirmed: 'உறுதி செய்யப்பட்டது',
    pending: 'நிலுவையில் உள்ளது',
    activePractice: 'செயலில் உள்ள பயிற்சி',
    experience: 'அனுபவம்',
    totalProcedures: 'மொத்த நடைமுறைகள்',
    education: 'கல்வி',
    certifications: 'சான்றிதழ்கள்',
    professionalBiography: 'தொழில்முறை வாழ்க்கை வரலாறு',
    workplaceInfo: 'பணியிட தகவல்',
    weeklyPatientVolume: 'வாராந்திர நோயாளி எண்ணிக்கை',
    diagnosticReports: 'கண்டறியும் அறிக்கைகள்',
    pharmacy: 'பார்மசி',
    scheduling: 'திட்டமிடல்',
    secureConsult: 'பாதுகாப்பான ஆலோசனை',
    clinicalNotes: 'மருத்துவ குறிப்புகள்',
    consultations: 'ஆலோசனைகள்',
    activeLink: 'பாதுகாப்பான செயலில் உள்ள இணைப்பு',
    typeMessage: 'மருத்துவ பதிலை தட்டச்சு செய்க...',
    aryanKumar: 'ஆர்யன் குமார்',
    elenaGilbert: 'எலினா கில்பர்ட்',
    stefanSalvatore: 'ஸ்டீபன் சால்வடோர்',
    damonSalvatore: 'டாமன் சால்வடோர்',
    bonnieBennett: 'போனி பென்னட்',
    janeDoe: 'ஜேன் டோ',
    emergencyCases: 'அவசர வழக்குகள்',
    normalCases: 'வழக்கமான வழக்குகள்',
    activeCasesUnderCare: 'உங்கள் பராமரிப்பில் உள்ள செயலில் உள்ள வழக்குகள்',
    generating: 'உருவாக்குகிறது...',
    automateNote: 'ஸ்மார்ட் ஸ்க்ரைப்',
    bloodType: 'இரத்த வகை',
    lastVisit: 'கடைசி வருகை',
    mockBloodType: 'ஓ பாசிட்டிவ்',
    noPatientsAssigned: 'எந்த நோயாளிகளும் ஒதுக்கப்படவில்லை',
    noSubjectsAssigned: 'தற்போது உங்கள் கவனிப்புக்கு நிர்வாகத்தால் எந்த நோயாளிகளும் ஒதுக்கப்படவில்லை. உங்கள் நோயாளிகளின் பட்டியலைப் பெற ஒத்திசைவு பொத்தானைப் பயன்படுத்தவும்.',
    electronicHealthRecord: 'மின்னணு சுகாதார பதிவு',
    demographics: 'புள்ளிவிவரங்கள்',
    contactLabel: 'தொடர்பு',
    familyGuardian: 'குடும்ப பாதுகாவலர்',
    biometrics: 'பயோமெட்ரிக்ஸ்',
    heartRate: 'இதய துடிப்பு',
    bloodPressure: 'இரத்த அழுத்தம்',
    clinicalProgressNotes: 'மருத்துவ முன்னேற்றக் குறிப்புகள்',
    formalMedicalRecords: 'முறையான மருத்துவ பதிவுகள்',
    addDiagnosis: 'நோயறிதலைச் சேர்க்கவும்',
    collapse: 'சுருக்கு',
    primaryImpression: 'முதன்மை அபிப்ராயம்',
    clinicalObservationDetails: 'மருத்துவ கண்காணிப்பு விவரங்கள்',
    commitToDataRegistry: 'தரவு பதிவேட்டில் சேமி',
    assessmentRecord: 'மதிப்பீட்டு பதிவு',
    verifiedByMedicalStaff: 'மருத்துவ ஊழியர்களால் சரிபார்க்கப்பட்டது',
    exportRecord: 'பதிவை ஏற்றுமதி செய்',
    noFormalRecords: 'எந்த முறையான மருத்துவ பதிவுகளும் கிடைக்கவில்லை.',
    activePrescriptions: 'செயலில் உள்ள மருந்துச் சீட்டுகள்',
    currentMedicationRegimen: 'தற்போதைய மருந்து முறை',
    newPrescription: 'புதிய மருந்து சீட்டு',
    medication: 'மருந்து',
    dosage: 'மருந்தளவு',
    duration: 'காலம்',
    issuePrescription: 'மருந்து சீட்டு வழங்கு',
    renew: 'புதுப்பிக்கவும்',
    noActivePrescriptions: 'எந்த செயலில் உள்ள மருந்துச் சீட்டுகளும் கிடைக்கவில்லை.',
    laboratoryResults: 'ஆய்வக முடிவுகள்',
    recentDiagnosticMetrics: 'சமீபத்திய கண்டறியும் அளவீடுகள்',
    newLabOrder: 'புதிய ஆய்வக கோரிக்கை',
    testType: 'சோதனை வகை',
    submitOrder: 'கோரிக்கையை சமர்ப்பி',
    noLabResults: 'எந்த ஆய்வக முடிவுகளும் கிடைக்கவில்லை.',
    upcomingAppointments: 'வரவிருக்கும் சந்திப்புகள்',
    scheduledConsultations: 'திட்டமிடப்பட்ட ஆலோசனைகள்',
    noUpcomingAppointments: 'எந்த வரவிருக்கும் சந்திப்புகளும் கிடைக்கவில்லை.',
    hypertensionStage1: 'உயர் இரத்த அழுத்தம் நிலை 1',
    hypertensionNotes: 'முறையான மதிப்பீடு தொடர்ச்சியாக அதிக அளவுகளைக் காட்டுகிறது. வாழ்க்கை முறை மாற்றச் செயல்முறையைத் தொடங்குகிறது.',
    seasonalAllergies: 'பருவகால ஒவ்வாமை',
    allergiesNotes: 'வசந்த காலங்களில் நோயாளி தொடர்ந்து ரைனிடிஸ் மற்றும் கண் அரிப்பு இருப்பதாக தெரிவிக்கிறார்.',
    lisinopril: 'லிசினோபிரில்',
    loratadine: 'லோராடாடின்',
    thirtyDays: '30 நாட்கள்',
    asNeeded: 'தேவைக்கேற்ப',
    lipidPanel: 'லிப்பிட் பேனல்',
    metabolicScreening: 'வளர்சிதை மாற்ற பரிசோதனை',
    completedStatus: 'முடிந்தது',
    orderedStatus: 'உத்தரவிடப்பட்டுள்ளது',
    cancel: 'ரத்துசெய்',
    totalCholesterol: 'மொத்த கொழுப்பு',
    abnormalStatus: 'நடைமுறைக்கு மாறான',
    fastingGlucose: 'வெறும் வயிற்றில் குளுக்கோஸ்',
    followUpConsultation: 'பின்தொடர்தல் ஆலோசனை',
  },
  gu: {
    dashboard: 'ડેશબોર્ડ',
    overview: 'ઝાંખી',
    patients: 'દર્દીઓ',
    messages: 'સુરક્ષિત સંદેશાઓ',
    profile: 'પ્રોફાઇલ',
    logout: 'લોગઆઉટ',
    goodMorning: 'શુભ સવાર',
    goodAfternoon: 'શુભ બપોર',
    goodEvening: 'શુભ સાંજ',
    welcomeBack: 'સ્વાગત છે',
    allSystemsNormal: 'તમામ સિસ્ટમ સામાન્ય છે',
    simulateEmergency: 'કટોકટીનું સિમ્યુલેશન કરો',
    todayAppointments: 'આજની એપોઇન્ટમેન્ટ્સ',
    criticalCases: 'ગંભીર કેસ',
    actionRequired: 'પગલાં જરૂરી છે',
    inPipeline: 'પાઇપલાઇનમાં',
    scheduled: 'નિર્ધારિત',
    priorityQueue: 'પ્રાધાન્યતા દર્દી કતાર',
    automatedSorting: 'સ્વચાલિત ગંભીરતા સોર્ટિંગ સક્રિય',
    newAdmission: 'નવો પ્રવેશ',
    noPendingCases: 'કોઈ બાકી ઉચ્ચ-પ્રાધાન્યતા કેસ નથી',
    waitingForSignals: 'ડાયગ્નોસ્ટિક સિગ્નલની રાહ જોઈ રહ્યા છીએ',
    analyze: 'વિશ્લેષણ કરો',
    totalActivePatients: 'કુલ સક્રિય દર્દીઓ',
    avgConsultations: 'સરેરાશ પરામર્શ / મહિનો',
    diagnosticAccuracy: 'ડાયગ્નોસ્ટિક ચોકસાઈ',
    patientSatisfaction: 'દર્દી સંતોષ',
    patientDirectory: 'દર્દી ડિરેક્ટરી',
    syncRegistry: 'ક્લિનિકલ રજિસ્ટ્રી સિંક કરો',
    activeCases: 'સક્રિય તબીબી કેસ',
    searchPatientsList: 'નામ અથવા ક્લિનિકલ સ્થિતિ દ્વારા શોધો...',
    noPatientsFound: 'તમારી શોધ સાથે મેળ ખાતા કોઈ દર્દીઓ મળ્યા નથી.',
    addPatient: 'દર્દી ઉમેરો',
    registryOf: 'રજિસ્ટ્રી',
    assignedSubjects: 'ક્લિનિકલ એડમિન દ્વારા સોંપેલ વિષયો',
    syncAdminAssignments: 'એડમિન સોંપણીઓ સિંક કરો',
    dr: 'ડો.',
    searchPatients: 'દર્દીઓ શોધો...',
    activePatients: 'સક્રિય દર્દીઓ',
    criticalAlerts: 'ગંભીર ચેતવણીઓ',
    pendingReviews: 'બાકી સમીક્ષાઓ',
    clinicalExcellence: 'ક્લિનિકલ શ્રેષ્ઠતા',
    recentActivity: 'તાજેતરની ક્લિનિકલ પ્રવૃત્તિ',
    emergency: 'કટોકટી',
    critical: 'ગંભીર',
    normal: 'સામાન્ય',
    confirmed: 'પુષ્ટિ થયેલ',
    pending: 'બાકી',
    activePractice: 'સક્રિય પ્રેક્ટિસ',
    experience: 'અનુભવ',
    totalProcedures: 'કુલ પ્રક્રિયાઓ',
    education: 'શિક્ષણ',
    certifications: 'પ્રમાણપત્રો',
    professionalBiography: 'વ્યાવસાયિક જીવનચરિત્ર',
    workplaceInfo: 'કાર્યસ્થળની માહિતી',
    weeklyPatientVolume: 'સાપ્તાહિક દર્દીઓની સંખ્યા',
    diagnosticReports: 'ડાયગ્નોસ્ટિક રિપોર્ટ્સ',
    pharmacy: 'ફાર્મસી',
    scheduling: 'શેડ્યુલિંગ',
    secureConsult: 'સુરક્ષિત પરામર્શ',
    clinicalNotes: 'ક્લિનિકલ નોંધો',
    consultations: 'પરામર્શ',
    activeLink: 'સુરક્ષિત સક્રિય લિંક',
    typeMessage: 'ક્લિનિકલ પ્રતિસાદ લખો...',
    aryanKumar: 'આર્યન કુમાર',
    elenaGilbert: 'એલેના ગિલ્બર્ટ',
    stefanSalvatore: 'સ્ટીફન સાલ્વાટોર',
    damonSalvatore: 'ડેમન સાલ્વાટોર',
    bonnieBennett: 'બોની બેનેટ',
    janeDoe: 'જેન ડો',
    emergencyCases: 'ઇમરજન્સી કેસ',
    normalCases: 'સામાન્ય કેસ',
    activeCasesUnderCare: 'તમારી સંભાળ હેઠળ સક્રિય કેસો',
    generating: 'બનાવી રહ્યું છે...',
    automateNote: 'સ્માર્ટ સ્ક્રાઇબ',
    bloodType: 'રક્ત પ્રકાર',
    lastVisit: 'છેલ્લી મુલાકાત',
    mockBloodType: 'ઓ પોઝિટિવ',
    noPatientsAssigned: 'કોઈ દર્દી સોંપવામાં આવ્યો નથી',
    noSubjectsAssigned: 'વહીવટીતંત્ર દ્વારા તમને હાલમાં કોઈ દર્દી સોંપવામાં આવ્યા નથી. તમારી યાદી મેળવવા માટે સિંક્રનાઇઝ બટનનો ઉપયોગ કરો.',
    electronicHealthRecord: 'ઇલેક્ટ્રોનિક હેલ્થ રેકોર્ડ',
    demographics: 'વસ્તી વિષયક',
    contactLabel: 'સંપર્ક',
    familyGuardian: 'કૌટુંબિક વાલી',
    biometrics: 'બાયોમેટ્રિક્સ',
    heartRate: 'હૃદયના ધબકારા',
    bloodPressure: 'બ્લડ પ્રેશર',
    clinicalProgressNotes: 'ક્લિનિકલ પ્રોગ્રેસ નોટ્સ',
    formalMedicalRecords: 'ઔપચારિક તબીબી રેકોર્ડ્સ',
    addDiagnosis: 'નિદાન ઉમેરો',
    collapse: 'સંકોચો',
    primaryImpression: 'પ્રાથમિક છાપ',
    clinicalObservationDetails: 'ક્લિનિકલ અવલોકનની વિગતો',
    commitToDataRegistry: 'ડેટા રજિસ્ટ્રીમાં સાચવો',
    assessmentRecord: 'મૂલ્યાંકન રેકોર્ડ',
    verifiedByMedicalStaff: 'તબીબી સ્ટાફ દ્વારા ચકાસાયેલ',
    exportRecord: 'રેકોર્ડ નિકાસ કરો',
    noFormalRecords: 'કોઈ ઔપચારિક ક્લિનિકલ રેકોર્ડ મળ્યો નથી.',
    activePrescriptions: 'સક્રિય પ્રિસ્ક્રિપ્શનો',
    currentMedicationRegimen: 'વર્તમાન દવા પદ્ધતિ',
    newPrescription: 'નવું પ્રિસ્ક્રિપ્શન',
    medication: 'દવા',
    dosage: 'ડોઝ',
    duration: 'સમયગાળો',
    issuePrescription: 'પ્રિસ્ક્રિપ્શન જારી કરો',
    renew: 'નવીકરણ કરો',
    noActivePrescriptions: 'કોઈ સક્રિય પ્રિસ્ક્રિપ્શનો મળ્યા નથી.',
    laboratoryResults: 'પ્રયોગશાળા પરિણામો',
    recentDiagnosticMetrics: 'તાજેતરના ડાયગ્નોસ્ટિક મેટ્રિક્સ',
    newLabOrder: 'નવો લેબ ઓર્ડર',
    testType: 'પરીક્ષણનો પ્રકાર',
    submitOrder: 'ઓર્ડર સબમિટ કરો',
    noLabResults: 'કોઈ પ્રયોગશાળા પરિણામો મળ્યાં નથી.',
    upcomingAppointments: 'આગામી એપોઇન્ટમેન્ટ્સ',
    scheduledConsultations: 'નિર્ધારિત પરામર્શ',
    noUpcomingAppointments: 'કોઈ આગામી એપોઇન્ટમેન્ટ્સ મળી નથી.',
    hypertensionStage1: 'હાઈ બ્લડ પ્રેશર સ્ટેજ 1',
    hypertensionNotes: 'પ્રણાલીગત મૂલ્યાંકન સતત વધેલા રીડિંગ્સ દર્શાવે છે. જીવનશૈલીમાં ફેરફાર માટેનો પ્રોટોકોલ શરૂ કરી રહ્યા છીએ.',
    seasonalAllergies: 'મોસમી એલર્જી',
    allergiesNotes: 'દર્દી વસંત ઋતુ દરમિયાન સતત રાઇનાઇટિસ અને ઓક્યુલર પ્ર્યુરિટસની જાણ કરે છે.',
    lisinopril: 'લિસિનોપ્રિલ',
    loratadine: 'લોરાટાડીન',
    thirtyDays: '30 દિવસ',
    asNeeded: 'જરૂર મુજબ',
    lipidPanel: 'લિપિડ પેનલ',
    metabolicScreening: 'મેટાબોલિક સ્ક્રીનિંગ',
    completedStatus: 'પૂર્ણ',
    orderedStatus: 'ઓર્ડર કરેલ',
    cancel: 'રદ કરો',
    totalCholesterol: 'કુલ કોલેસ્ટ્રોલ',
    abnormalStatus: 'અસામાન્ય',
    fastingGlucose: 'ફાસ્ટિંગ ગ્લુકોઝ',
    followUpConsultation: 'ફોલો-અપ પરામર્શ',
  },
  kn: {
    dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    overview: 'ಅವಲೋಕನ',
    patients: 'ರೋಗಿಗಳು',
    messages: 'ಸುರಕ್ಷಿತ ಸಂದೇಶಗಳು',
    profile: 'ಪ್ರೊಫೈಲ್',
    logout: 'ಲಾಗ್ಔಟ್',
    goodMorning: 'ಶುಭೋದಯ',
    goodAfternoon: 'ಶುಭ ಮಧ್ಯಾಹ್ನ',
    goodEvening: 'ಶುಭ ಸಂಜೆ',
    welcomeBack: 'ಸ್ವಾಗತ',
    allSystemsNormal: 'ಎಲ್ಲಾ ವ್ಯವಸ್ಥೆಗಳು ಸಾಮಾನ್ಯ ಮಿತಿಯೊಳಗೆ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತಿವೆ',
    simulateEmergency: 'ತುರ್ತು ಪರಿಸ್ಥಿತಿಯನ್ನು ಅನುಕರಿಸಿ',
    todayAppointments: 'ಇಂದಿನ ನೇಮಕಾತಿಗಳು',
    criticalCases: 'ನಿರ್ಣಾಯಕ ಪ್ರಕರಣಗಳು',
    actionRequired: 'ಕ್ರಮದ ಅಗತ್ಯವಿದೆ',
    inPipeline: 'ಪೈಪ್‌ಲೈನ್‌ನಲ್ಲಿದೆ',
    scheduled: 'ನಿಗದಿಯಾಗಿದೆ',
    priorityQueue: 'ಆದ್ಯತೆಯ ರೋಗಿ ಸರತಿ',
    automatedSorting: 'ಸ್ವಯಂಚಾಲಿತ ತೀವ್ರತೆ ವಿಂಗಡಣೆ ಸಕ್ರಿಯವಾಗಿದೆ',
    newAdmission: 'ಹೊಸ ದಾಖಲಾತಿ',
    noPendingCases: 'ಯಾವುದೇ ಬಾಕಿ ಇರುವ ಉನ್ನತ-ಆದ್ಯತೆಯ ಪ್ರಕರಣಗಳಿಲ್ಲ',
    waitingForSignals: 'ಡಯಾಗ್ನೋಸ್ಟಿಕ್ ಸಂಕೇತಗಳಿಗಾಗಿ ಕಾಯಲಾಗುತ್ತಿದೆ',
    analyze: 'ವಿಶ್ಲೇಷಿಸಿ',
    totalActivePatients: 'ಒಟ್ಟು ಸಕ್ರಿಯ ರೋಗಿಗಳು',
    avgConsultations: 'ಸರಾಸರಿ ಸಮಾಲೋಚನೆಗಳು / ತಿಂಗಳು',
    diagnosticAccuracy: 'ರೋಗನಿರ್ಣಯ ನಿಖರತೆ',
    patientSatisfaction: 'ರೋಗಿ ತೃಪ್ತಿ',
    patientDirectory: 'ರೋಗಿ ಡೈರೆಕ್ಟರಿ',
    syncRegistry: 'ಕ್ಲಿನಿಕಲ್ ರಿಜಿಸ್ಟ್ರಿಯನ್ನು ಸಿಂಕ್ ಮಾಡಿ',
    activeCases: 'ಸಕ್ರಿಯ ವೈದ್ಯಕೀಯ ಪ್ರಕರಣಗಳು',
    searchPatientsList: 'ಹೆಸರು ಅಥವಾ ಕ್ಲಿನಿಕಲ್ ಸ್ಥಿತಿಯಿಂದ ಹುಡುಕಿ...',
    noPatientsFound: 'ನಿಮ್ಮ ಹುಡುಕಾಟ ಮಾನದಂಡಗಳಿಗೆ ಹೊಂದುವ ಯಾವುದೇ ರೋಗಿಗಳು ಕಂಡುಬಂದಿಲ್ಲ.',
    addPatient: 'ರೋಗಿಯನ್ನು ಸೇರಿಸಿ',
    registryOf: 'ರಿಜಿಸ್ಟ್ರಿ',
    assignedSubjects: 'ಕ್ಲಿನಿಕಲ್ ಅಡ್ಮಿನ್ ನಿಯೋಜಿಸಿದ ರೋಗಿಗಳು',
    syncAdminAssignments: 'ಅಡ್ಮಿನ್ ನಿಯೋಜನೆಗಳನ್ನು ಸಿಂಕ್ ಮಾಡಿ',
    dr: 'ಡಾ.',
    searchPatients: 'ರೋಗಿಗಳನ್ನು ಹುಡುಕಿ...',
    activePatients: 'ಸಕ್ರಿಯ ರೋಗಿಗಳು',
    criticalAlerts: 'ನಿರ್ಣಾಯಕ ಎಚ್ಚರಿಕೆಗಳು',
    pendingReviews: 'ಬಾಕಿ ವಿಮರ್ಶೆಗಳು',
    clinicalExcellence: 'ಕ್ಲಿನಿಕಲ್ ಶ್ರೇಷ್ಠತೆ',
    recentActivity: 'ಇತ್ತೀಚಿನ ಕ್ಲಿನಿಕಲ್ ಚಟುವಟಿಕೆ',
    emergency: 'ತುರ್ತು ಪರಿಸ್ಥಿತಿ',
    critical: 'ನಿರ್ಣಾಯಕ',
    normal: 'ಸಾಮಾನ್ಯ',
    confirmed: 'ದೃಢಪಡಿಸಲಾಗಿದೆ',
    pending: 'ಬಾಕಿಯಿದೆ',
    activePractice: 'ಸಕ್ರಿಯ ಅಭ್ಯಾಸ',
    experience: 'ಅನುಭವ',
    totalProcedures: 'ಒಟ್ಟು ಕಾರ್ಯವಿಧಾನಗಳು',
    education: 'ಶಿಕ್ಷಣ',
    certifications: 'ಪ್ರಮಾಣಪತ್ರಗಳು',
    professionalBiography: 'ವೃತ್ತಿಪರ ಜೀವನ ಚರಿತ್ರೆ',
    workplaceInfo: 'ಕೆಲಸದ ಸ್ಥಳದ ಮಾಹಿತಿ',
    weeklyPatientVolume: 'ವಾರದ ರೋಗಿಗಳ ಪ್ರಮಾಣ',
    diagnosticReports: 'ರೋಗನಿರ್ಣಯ ವರದಿಗಳು',
    pharmacy: 'ಫಾರ್ಮಸಿ',
    scheduling: 'ವೇಳಾಪಟ್ಟಿ',
    secureConsult: 'ಸುರಕ್ಷಿತ ಸಮಾಲೋಚನೆ',
    clinicalNotes: 'ಕ್ಲಿನಿಕಲ್ ಟಿಪ್ಪಣಿಗಳು',
    consultations: 'ಸಮಾಲೋಚನೆಗಳು',
    activeLink: 'ಸುರಕ್ಷಿತ ಸಕ್ರಿಯ ಲಿಂಕ್',
    typeMessage: 'ಕ್ಲಿನಿಕಲ್ ಪ್ರತಿಕ್ರಿಯೆಯನ್ನು ಟೈಪ್ ಮಾಡಿ...',
    aryanKumar: 'ಆರ್ಯನ್ ಕುಮಾರ್',
    elenaGilbert: 'ಎಲೆನಾ ಗಿಲ್ಬರ್ಟ್',
    stefanSalvatore: 'ಸ್ಟೀಫನ್ ಸಾಲ್ವಟೋರ್',
    damonSalvatore: 'ಡಾಮನ್ ಸಾಲ್ವಟೋರ್',
    bonnieBennett: 'ಬೋನಿ ಬೆನೆಟ್',
    janeDoe: 'ಜೇನ್ ಡೋ',
    emergencyCases: 'ತುರ್ತು ಪ್ರಕರಣಗಳು',
    normalCases: 'ಸಾಮಾನ್ಯ ಪ್ರಕರಣಗಳು',
    activeCasesUnderCare: 'ನಿಮ್ಮ ಆರೈಕೆಯಲ್ಲಿರುವ ಸಕ್ರಿಯ ಪ್ರಕರಣಗಳು',
    generating: 'ರಚಿಸಲಾಗುತ್ತಿದೆ...',
    automateNote: 'ಸ್ಮಾರ್ಟ್ ಸ್ಕ್ರೈಬ್',
    bloodType: 'ರಕ್ತದ ಗುಂಪು',
    lastVisit: 'ಕೊನೆಯ ಭೇಟಿ',
    mockBloodType: 'ಓ ಪಾಸಿಟಿವ್',
    noPatientsAssigned: 'ಯಾವುದೇ ರೋಗಿಗಳನ್ನು ನಿಯೋಜಿಸಲಾಗಿಲ್ಲ',
    noSubjectsAssigned: 'ಪ್ರಸ್ತುತ ಆಡಳಿತದಿಂದ ನಿಮ್ಮ ಆರೈಕೆಗೆ ಯಾವುದೇ ರೋಗಿಗಳನ್ನು ನಿಯೋಜಿಸಲಾಗಿಲ್ಲ. ನಿಮ್ಮ ಪಟ್ಟಿಯನ್ನು ಪಡೆಯಲು ಸಿಂಕ್ರೊನೈಸ್ ಬಟನ್ ಬಳಸಿ.',
    electronicHealthRecord: 'ಎಲೆಕ್ಟ್ರಾನಿಕ್ ಆರೋಗ್ಯ ದಾಖಲೆ',
    demographics: 'ಜನಸಂಖ್ಯಾಶಾಸ್ತ್ರ',
    contactLabel: 'ಸಂಪರ್ಕ',
    familyGuardian: 'ಕುಟುಂಬ ಪೋಷಕರು',
    biometrics: 'ಬಯೋಮೆಟ್ರಿಕ್ಸ್',
    heartRate: 'ಹೃದಯ ಬಡಿತ',
    bloodPressure: 'ರಕ್ತದೊತ್ತಡ',
    clinicalProgressNotes: 'ಕ್ಲಿನಿಕಲ್ ಪ್ರಗತಿ ಟಿಪ್ಪಣಿಗಳು',
    formalMedicalRecords: 'ಔಪಚಾರಿಕ ವೈದ್ಯಕೀಯ ದಾಖಲೆಗಳು',
    addDiagnosis: 'ರೋಗನಿರ್ಣಯವನ್ನು ಸೇರಿಸಿ',
    collapse: 'ಹಿಂದಕ್ಕೆ ಮಡಚಿ',
    primaryImpression: 'ಪ್ರಾಥಮಿಕ ಅನಿಸಿಕೆ',
    clinicalObservationDetails: 'ಕ್ಲಿನಿಕಲ್ ವೀಕ್ಷಣೆ ವಿವರಗಳು',
    commitToDataRegistry: 'ಡೇಟಾ ರಿಜಿಸ್ಟ್ರಿಯಲ್ಲಿ ಉಳಿಸಿ',
    assessmentRecord: 'ಮೌಲ್ಯಮಾಪನ ದಾಖಲೆ',
    verifiedByMedicalStaff: 'ವೈದ್ಯಕೀಯ ಸಿಬ್ಬಂದಿಗಳಿಂದ ಪರಿಶೀಲಿಸಲಾಗಿದೆ',
    exportRecord: 'ದಾಖಲೆಯನ್ನು ರಫ್ತು ಮಾಡಿ',
    noFormalRecords: 'ಯಾವುದೇ ಔಪಚಾರಿಕ ಕ್ಲಿನಿಕಲ್ ದಾಖಲೆಗಳು ಕಂಡುಬಂದಿಲ್ಲ.',
    activePrescriptions: 'ಸಕ್ರಿಯ ಔಷಧಿ ಚೀಟಿಗಳು',
    currentMedicationRegimen: 'ಪ್ರಸ್ತುತ ಔಷಧಿ ಕಟ್ಟುಪಾಡು',
    newPrescription: 'ಹೊಸ ಔಷಧಿ ಚೀಟಿ',
    medication: 'ಔಷಧಿ',
    dosage: 'ಡೋಸೇಜ್',
    duration: 'ಅವಧಿ',
    issuePrescription: 'ಔಷಧಿ ಚೀಟಿ ವಿತರಿಸಿ',
    renew: 'ನವೀಕರಿಸಿ',
    noActivePrescriptions: 'ಯಾವುದೇ ಸಕ್ರಿಯ ಔಷಧಿ ಚೀಟಿಗಳು ಕಂಡುಬಂದಿಲ್ಲ.',
    laboratoryResults: 'ಪ್ರಯೋಗಾಲಯದ ಫಲಿತಾಂಶಗಳು',
    recentDiagnosticMetrics: 'ಇತ್ತೀಚಿನ ರೋಗನಿರ್ಣಯದ ಮೆಟ್ರಿಕ್‌ಗಳು',
    newLabOrder: 'ಹೊಸ ಲ್ಯಾಬ್ ಆರ್ಡರ್',
    testType: 'ಪರೀಕ್ಷೆಯ ಪ್ರಕಾರ',
    submitOrder: 'ಆರ್ಡರ್ ಸಲ್ಲಿಸಿ',
    noLabResults: 'ಯಾವುದೇ ಪ್ರಯೋಗಾಲಯದ ಫಲಿತಾಂಶಗಳು ಕಂಡುಬಂದಿಲ್ಲ.',
    upcomingAppointments: 'ಮುಂಬರುವ ನೇಮಕಾತಿಗಳು',
    scheduledConsultations: 'ನಿಗದಿತ ಸಮಾಲೋಚನೆಗಳು',
    noUpcomingAppointments: 'ಯಾವುದೇ ಮುಂಬರುವ ನೇಮಕಾತಿಗಳು ಕಂಡುಬಂದಿಲ್ಲ.',
    hypertensionStage1: 'ಅಧಿಕ ರಕ್ತದೊತ್ತಡ ಹಂತ 1',
    hypertensionNotes: 'ವ್ಯವಸ್ಥಿತ ಮೌಲ್ಯಮಾಪನವು ನಿರಂತರವಾಗಿ ಹೆಚ್ಚಿದ ಓದುವಿಕೆಗಳನ್ನು ತೋರಿಸುತ್ತದೆ. ಜೀವನಶೈಲಿ ಮಾರ್ಪಾಡು ಪ್ರೋಟೋಕಾಲ್ ಅನ್ನು ಪ್ರಾರಂಭಿಸುವುದು.',
    seasonalAllergies: 'ಋತುಮಾನದ ಅಲರ್ಜಿಗಳು',
    allergiesNotes: 'ರೋಗಿಯು ವಸಂತ ಋತುವಿನಲ್ಲಿ ನಿರಂತರ ಮೂಗು ಮತ್ತು ಕಣ್ಣಿನ ತುರಿಕೆಯನ್ನು ವರದಿ ಮಾಡುತ್ತಾನೆ.',
    lisinopril: 'ಲಿಸಿನೊಪ್ರಿಲ್',
    loratadine: 'ಲೊರಾಟಾಡಿನ್',
    thirtyDays: '30 ದಿನಗಳು',
    asNeeded: 'ಅಗತ್ಯವಿದ್ದಂತೆ',
    lipidPanel: 'ಲಿಪಿಡ್ ಪ್ಯಾನಲ್',
    metabolicScreening: 'ಮೆಟಬಾಲಿಕ್ ಸ್ಕ್ರೀನಿಂಗ್',
    completedStatus: 'ಪೂರ್ಣಗೊಂಡಿದೆ',
    orderedStatus: 'ಆದೇಶಿಸಲಾಗಿದೆ',
    cancel: 'ರದ್ದುಮಾಡಿ',
    totalCholesterol: 'ಒಟ್ಟು ಕೊಲೆಸ್ಟ್ರಾಲ್',
    abnormalStatus: 'ಅಸಹಜ',
    fastingGlucose: 'ಉಪವಾಸದ ಗ್ಲೂಕೋಸ್',
    followUpConsultation: 'ಫಾಲೋ-ಅಪ್ ಸಮಾಲೋಚನೆ',
  },
  ml: {
    dashboard: 'ഡാഷ്ബോർഡ്',
    overview: 'അവലോകനം',
    patients: 'രോഗികൾ',
    messages: 'സുരക്ഷിത സന്ദേശങ്ങൾ',
    profile: 'പ്രൊഫൈൽ',
    logout: 'ലോഗൗട്ട്',
    goodMorning: 'സുപ്രഭാതം',
    goodAfternoon: 'ശുഭ ഉച്ചതിരിഞ്ഞ്',
    goodEvening: 'ശുഭ സായാഹ്നം',
    welcomeBack: 'സ്വാഗതം',
    allSystemsNormal: 'എല്ലാ സിസ്റ്റങ്ങളും സാധാരണ നിലയിലാണ് ഓടുന്നത്',
    simulateEmergency: 'അടിയന്തരാവസ്ഥ അനുകരിക്കുക',
    todayAppointments: 'ഇന്നത്തെ അപ്പോയിന്റ്മെന്റുകൾ',
    criticalCases: 'നിർണ്ണായക കേസുകൾ',
    actionRequired: 'നടപടി ആവശ്യമാണ്',
    inPipeline: 'പൈപ്പ്ലൈനിൽ',
    scheduled: 'ഷെഡ്യൂൾ ചെയ്‌തു',
    priorityQueue: 'മുൻഗണനാ രോഗി ക്യൂ',
    automatedSorting: 'ഓട്ടോമേറ്റഡ് തീവ്രത സോർട്ടിംഗ് സജീവമാണ്',
    newAdmission: 'പുതിയ പ്രവേശനം',
    noPendingCases: 'തീർപ്പാക്കാത്ത ഉയർന്ന മുൻഗണനാ കേസുകളൊന്നുമില്ല',
    waitingForSignals: 'ഡയഗ്നോസ്റ്റിക് സിഗ്നലുകൾക്കായി കാത്തിരിക്കുന്നു',
    analyze: 'വിശകലനം ചെയ്യുക',
    totalActivePatients: 'ആകെ സജീവ രോഗികൾ',
    avgConsultations: 'ശരാശരി കൺസൾട്ടേഷനുകൾ / മാസം',
    diagnosticAccuracy: 'ഡയഗ്നോസ്റ്റിക് കൃത്യത',
    patientSatisfaction: 'രോഗിയുടെ സംതൃപ്തി',
    patientDirectory: 'പേഷ്യന്റ് ഡയറക്ടറി',
    syncRegistry: 'ക്ലിനിക്കൽ രജിസ്ട്രി സമന്വയിപ്പിക്കുക',
    activeCases: 'സജീവ മെഡിക്കൽ കേസുകൾ',
    searchPatientsList: 'പേരോ ക്ലിനിക്കൽ നിലയോ ഉപയോഗിച്ച് തിരയുക...',
    noPatientsFound: 'നിങ്ങളുടെ തിരയൽ മാനദണ്ഡങ്ങളുമായി പൊരുത്തപ്പെടുന്ന രോഗികളില്ല.',
    addPatient: 'രോഗിയെ ചേർക്കുക',
    registryOf: 'രജിസ്ട്രി',
    assignedSubjects: 'ക്ലിനിക്കൽ അഡ്മിൻ നിയോഗിച്ച രോഗികൾ',
    syncAdminAssignments: 'അഡ്മിൻ അസൈൻമെന്റുകൾ സമന്വയിപ്പിക്കുക',
    dr: 'ഡോ.',
    searchPatients: 'രോഗികളെ തിരയുക...',
    activePatients: 'സജീവ രോഗികൾ',
    criticalAlerts: 'നിർണ്ണായക അലേർട്ടുകൾ',
    pendingReviews: 'തീർപ്പുകൽപ്പിക്കാത്ത അവലോകനങ്ങൾ',
    clinicalExcellence: 'ക്ലിനിക്കൽ മികവ്',
    recentActivity: 'സമീപകാല ക്ലിനിക്കൽ പ്രവർത്തനം',
    emergency: 'അടിയന്തിരാവസ്ഥ',
    critical: 'നിർണ്ണായകമാണ്',
    normal: 'സാധാരണ',
    confirmed: 'സ്ഥിരീകരിച്ചു',
    pending: 'തീർപ്പുകൽപ്പിക്കാത്ത',
    activePractice: 'സജീവ പരിശീലനം',
    experience: 'പരിചയം',
    totalProcedures: 'മൊത്തം നടപടിക്രമങ്ങൾ',
    education: 'വിദ്യാഭ്യാസം',
    certifications: 'സർട്ടിഫിക്കേഷനുകൾ',
    professionalBiography: 'പ്രൊഫഷണൽ ജീവചരിത്രം',
    workplaceInfo: 'ജോലിസ്ഥലത്തെ വിവരങ്ങൾ',
    weeklyPatientVolume: 'പ്രതിവാര രോഗികളുടെ എണ്ണം',
    diagnosticReports: 'ഡയഗ്നോസ്റ്റിക് റിപ്പോർട്ടുകൾ',
    pharmacy: 'ഫാർമസി',
    scheduling: 'ഷെഡ്യൂളിംഗ്',
    secureConsult: 'സുരക്ഷിത കൺസൾട്ടേഷൻ',
    clinicalNotes: 'ക്ലിനിക്കൽ കുറിപ്പുകൾ',
    consultations: 'കൺസൾട്ടേഷനുകൾ',
    activeLink: 'സുരക്ഷിത സജീവ ലിങ്ക്',
    typeMessage: 'ക്ലിനിക്കൽ പ്രതികരണം ടൈപ്പ് ചെയ്യുക...',
    aryanKumar: 'ആര്യൻ കുമാർ',
    elenaGilbert: 'എലീന ഗിൽബർട്ട്',
    stefanSalvatore: 'സ്റ്റീഫൻ സാൽവറ്റോർ',
    damonSalvatore: 'ഡാമൺ സാൽവറ്റോർ',
    bonnieBennett: 'ബോണി ബെന്നറ്റ്',
    janeDoe: 'ജെയ്ൻ ഡോ',
    emergencyCases: 'അടിയന്തര കേസുകൾ',
    normalCases: 'സാധാരണ കേസുകൾ',
    activeCasesUnderCare: 'നിങ്ങളുടെ പരിചരണത്തിലുള്ള സജീവ കേസുകൾ',
    generating: 'സൃഷ്ടിക്കുന്നു...',
    automateNote: 'സ്മാർട്ട് സ്ക്രൈബ്',
    bloodType: 'രക്തഗ്രൂപ്പ്',
    lastVisit: 'അവസാന സന്ദർശനം',
    mockBloodType: 'ഒ പോസിറ്റീവ്',
    noPatientsAssigned: 'രോഗികളെയൊന്നും നിയോഗിച്ചിട്ടില്ല',
    noSubjectsAssigned: 'നിലവിൽ നിങ്ങളുടെ പരിചരണത്തിനായി ഭരണസമിതി രോഗികളെയൊന്നും നിയോഗിച്ചിട്ടില്ല. നിങ്ങളുടെ പട്ടിക ലഭിക്കാൻ സിൻക്രൊണൈസ് ബട്ടൺ ഉപയോഗിക്കുക.',
    electronicHealthRecord: 'ഇലക്ട്രോണിക് ഹെൽത്ത് റെക്കോർഡ്',
    demographics: 'ജനസംഖ്യാശാസ്ത്രം',
    contactLabel: 'ബന്ധപ്പെടുക',
    familyGuardian: 'കുടുംബ രക്ഷാധികാരി',
    biometrics: 'ബയോമെട്രിക്സ്',
    heartRate: 'ഹൃദയമിടിപ്പ്',
    bloodPressure: 'രക്തസമ്മർദ്ദം',
    clinicalProgressNotes: 'ക്ലിനിക്കൽ പുരോഗതി കുറിപ്പുകൾ',
    formalMedicalRecords: 'ഔപചാരിക മെഡിക്കൽ റെക്കോർഡുകൾ',
    addDiagnosis: 'രോഗനിർണയം ചേർക്കുക',
    collapse: 'ചുരുക്കുക',
    primaryImpression: 'പ്രാഥമിക അഭിപ്രായം',
    clinicalObservationDetails: 'ക്ലിനിക്കൽ നിരീക്ഷണ വിശദാംശങ്ങൾ',
    commitToDataRegistry: 'ഡാറ്റാ രജിസ്ട്രിയിൽ സംരക്ഷിക്കുക',
    assessmentRecord: 'വിലയിരുത്തൽ രേഖ',
    verifiedByMedicalStaff: 'മെഡിക്കൽ സ്റ്റാഫ് പരിശോധിച്ചു',
    exportRecord: 'രേഖ എക്‌സ്‌പോർട്ട് ചെയ്യുക',
    noFormalRecords: 'ഔപചാരിക ക്ലിനിക്കൽ രേഖകളൊന്നും കണ്ടെത്തിയില്ല.',
    activePrescriptions: 'സജീവ കുറിപ്പടികൾ',
    currentMedicationRegimen: 'നിലവിലെ ഔഷധക്രമം',
    newPrescription: 'പുതിയ കുറിപ്പടി',
    medication: 'മരുന്ന്',
    dosage: 'അളവ്',
    duration: 'കാലാവധി',
    issuePrescription: 'കുറിപ്പടി നൽകുക',
    renew: 'പുതുക്കുക',
    noActivePrescriptions: 'സജീവമായ കുറിപ്പടികളൊന്നും കണ്ടെത്തിയില്ല.',
    laboratoryResults: 'ലബോറട്ടറി ഫലങ്ങൾ',
    recentDiagnosticMetrics: 'സമീപകാല ഡയഗ്നോസ്റ്റിക് മെട്രിക്സ്',
    newLabOrder: 'പുതിയ ലാബ് ഓർഡർ',
    testType: 'പരിശോധന തരം',
    submitOrder: 'ഓർഡർ സമർപ്പിക്കുക',
    noLabResults: 'ലബോറട്ടറി ഫലങ്ങളൊന്നും കണ്ടെത്തിയില്ല.',
    upcomingAppointments: 'വരാനിരിക്കുന്ന അപ്പോയിന്റ്‌മെന്റുകൾ',
    scheduledConsultations: 'നിശ്ചയിച്ചിട്ടുള്ള കൂടിയാലോചനകൾ',
    noUpcomingAppointments: 'വരാനിരിക്കുന്ന അപ്പോയിന്റ്‌മെന്റുകളൊന്നും കണ്ടെത്തിയില്ല.',
    hypertensionStage1: 'രക്താതിമർദ്ദം ഘട്ടം 1',
    hypertensionNotes: 'സിസ്റ്റമിക് വിലയിരുത്തൽ സ്ഥിരമായി ഉയർന്ന റീഡിംഗുകൾ കാണിക്കുന്നു. ജീവിതശൈലി മാറ്റ പരിപാടി ആരംഭിക്കുന്നു.',
    seasonalAllergies: 'കാലിക അലർജികൾ',
    allergiesNotes: 'രോഗി വസന്തകാലത്ത് നിരന്തരമായ നാസികാ, കണ്ണ് ചൊറിച്ചിൽ റിപ്പോർട്ട് ചെയ്യുന്നു.',
    lisinopril: 'ലിസിനോപ്രിൽ',
    loratadine: 'ലൊറാറ്റാഡിൻ',
    thirtyDays: '30 ദിവസം',
    asNeeded: 'ആവശ്യാനുസരണം',
    lipidPanel: 'ലിപിഡ് പാനൽ',
    metabolicScreening: 'മെറ്റബോളിക് സ്ക്രീനിംഗ്',
    completedStatus: 'പൂർത്തിയായി',
    orderedStatus: 'ഓർഡർ ചെയ്തു',
    cancel: 'റദ്ദാക്കുക',
    totalCholesterol: 'ആകെ കൊളസ്ട്രോൾ',
    abnormalStatus: 'അസാധാരണമായ',
    fastingGlucose: 'ഫാസ്റ്റിംഗ് ഗ്ലൂക്കോസ്',
    followUpConsultation: 'തുടർ കൂടിയാലോചന',
  },
  pa: {
    dashboard: 'ਡੈਸ਼ਬੋਰਡ',
    overview: 'ਸੰਖੇਪ ਜਾਣਕਾਰੀ',
    patients: 'ਮਰੀਜ਼',
    messages: 'ਸੁਰੱਖਿਅਤ ਸੁਨੇਹੇ',
    profile: 'ਪ੍ਰੋਫਾਈਲ',
    logout: 'ਲੌਗਆਊਟ',
    goodMorning: 'ਸ਼ੁਭ ਸਵੇਰ',
    goodAfternoon: 'ਸ਼ੁਭ ਦੁਪਹਿਰ',
    goodEvening: 'ਸ਼ੁਭ ਸ਼ਾਮ',
    welcomeBack: 'ਜੀ ਆਇਆਂ ਨੂੰ',
    allSystemsNormal: 'ਸਾਰੇ ਸਿਸਟਮ ਆਮ ਹਨ',
    simulateEmergency: 'ਐਮਰਜੈਂਸੀ ਸਿਮੂਲੇਟ ਕਰੋ',
    todayAppointments: 'ਅੱਜ ਦੀਆਂ ਮੁਲਾਕਾਤਾਂ',
    criticalCases: 'ਗੰਭੀਰ ਮਾਮਲੇ',
    actionRequired: 'ਕਾਰਵਾਈ ਦੀ ਲੋੜ ਹੈ',
    inPipeline: 'ਪਾਈਪਲਾਈਨ ਵਿੱਚ',
    scheduled: 'ਨਿਰਧਾਰਤ',
    priorityQueue: 'ਤਰਜੀਹੀ ਮਰੀਜ਼ ਕਤਾਰ',
    automatedSorting: 'ਸਵੈਚਾਲਤ ਗੰਭੀਰਤਾ ਛਾਂਟੀ ਸਰਗਰਮ ਹੈ',
    newAdmission: 'ਨਵਾਂ ਦਾਖਲਾ',
    noPendingCases: 'ਕੋਈ ਬਕਾਇਆ ਉੱਚ-ਤਰਜੀਹ ਵਾਲਾ ਮਾਮਲਾ ਨਹੀਂ',
    waitingForSignals: 'ਨਿਦਾਨਕ ਸੰਕੇਤਾਂ ਦੀ ਉਡੀਕ ਕੀਤੀ ਜਾ ਰਹੀ ਹੈ',
    analyze: 'ਵਿਸ਼ਲੇਸ਼ਣ ਕਰੋ',
    totalActivePatients: 'ਕੁੱਲ ਸਰਗਰਮ ਮਰੀਜ਼',
    avgConsultations: 'ਔਸਤ ਸਲਾਹ-ਮਸ਼ਵਰੇ / ਮਹੀਨਾ',
    diagnosticAccuracy: 'ਨਿਦਾਨਕ ਸ਼ੁੱਧਤਾ',
    patientSatisfaction: 'ਮਰੀਜ਼ ਦੀ ਸੰਤੁਸ਼ਟੀ',
    patientDirectory: 'ਮਰੀਜ਼ ਡਾਇਰੈਕਟਰੀ',
    syncRegistry: 'ਕਲੀਨਿਕਲ ਰਜਿਸਟਰੀ ਸਿੰਕ ਕਰੋ',
    activeCases: 'ਸਰਗਰਮ ਮੈਡੀਕਲ ਮਾਮਲੇ',
    searchPatientsList: 'ਨਾਮ ਜਾਂ ਕਲੀਨਿਕਲ ਸਥਿਤੀ ਦੁਆਰਾ ਖੋਜੋ...',
    noPatientsFound: 'ਤੁਹਾਡੇ ਖੋਜ ਮਾਪਦੰਡਾਂ ਨਾਲ ਮੇਲ ਖਾਂਦਾ ਕੋਈ ਮਰੀਜ਼ ਨਹੀਂ ਮਿਲਿਆ।',
    addPatient: 'ਮਰੀਜ਼ ਸ਼ਾਮਲ ਕਰੋ',
    registryOf: 'ਰਜਿਸਟਰੀ',
    assignedSubjects: 'ਕਲੀਨਿਕਲ ਐਡਮਿਨ ਦੁਆਰਾ ਨਿਰਧਾਰਤ ਮਰੀਜ਼',
    syncAdminAssignments: 'ਐਡਮਿਨ ਅਸਾਈਨਮੈਂਟ ਸਿੰਕ ਕਰੋ',
    dr: 'ਡਾ.',
    searchPatients: 'ਮਰੀਜ਼ਾਂ ਦੀ ਭਾਲ ਕਰੋ...',
    activePatients: 'ਸਰਗਰਮ ਮਰੀਜ਼',
    criticalAlerts: 'ਗੰਭੀਰ ਚੇਤਾਵਨੀਆਂ',
    pendingReviews: 'ਬਕਾਇਆ ਸਮੀਖਿਆਵਾਂ',
    clinicalExcellence: 'ਕਲੀਨਿਕਲ ਉੱਤਮਤਾ',
    recentActivity: 'ਹਾਲੀਆ ਕਲੀਨਿਕਲ ਗਤੀਵਿਧੀ',
    emergency: 'ਐਮਰਜੈਂਸੀ',
    critical: 'ਗੰਭੀਰ',
    normal: 'ਆਮ',
    confirmed: 'ਪੁਸ਼ਟੀ ਕੀਤੀ ਗਈ',
    pending: 'ਬਕਾਇਆ',
    activePractice: 'ਸਰਗਰਮ ਅਭਿਆਸ',
    experience: 'ਤਜਰਬਾ',
    totalProcedures: 'ਕੁੱਲ ਪ੍ਰਕਿਰਿਆਵਾਂ',
    education: 'ਸਿੱਖਿਆ',
    certifications: 'ਪ੍ਰਮਾਣ ਪੱਤਰ',
    professionalBiography: 'ਪੇਸ਼ੇਵਰ ਜੀਵਨੀ',
    workplaceInfo: 'ਕਾਰਜ ਸਥਾਨ ਦੀ ਜਾਣਕਾਰੀ',
    weeklyPatientVolume: 'ਹਫਤਾਵਾਰੀ ਮਰੀਜ਼ਾਂ ਦੀ ਗਿਣਤੀ',
    diagnosticReports: 'ਨਿਦਾਨਕ ਰਿਪੋਰਟਾਂ',
    pharmacy: 'ਫਾਰਮੇਸੀ',
    scheduling: 'ਸ਼ਡਿਊਲਿੰਗ',
    secureConsult: 'ਸੁਰੱਖਿਅਤ ਸਲਾਹ-ਮਸ਼ਵਰਾ',
    clinicalNotes: 'ਕਲੀਨਿਕਲ ਨੋਟਸ',
    consultations: 'ਸਲਾਹ-ਮਸ਼ਵਰੇ',
    activeLink: 'ਸੁਰੱਖਿਅਤ ਸਰਗਰਮ ਲਿੰਕ',
    typeMessage: 'ਕਲੀਨਿਕਲ ਪ੍ਰਤੀਕਿਰਿਆ ਟਾਈਪ ਕਰੋ...',
    emergencyCases: 'ਐਮਰਜੈਂਸੀ ਮਾਮਲੇ',
    normalCases: 'ਆਮ ਮਾਮਲੇ',
    activeCasesUnderCare: 'ਤੁਹਾਡੀ ਦੇਖਭਾਲ ਅਧੀਨ ਸਰਗਰਮ ਮਾਮਲੇ',
    generating: 'ਬਣਾ ਰਿਹਾ ਹੈ...',
    automateNote: 'ਸਮਾਰਟ ਸਬ',
    aryanKumar: 'ਆਰੀਅਨ ਕੁਮਾਰ',
    elenaGilbert: 'ਏਲੇਨਾ ਗਿਲਬਰਟ',
    stefanSalvatore: 'ਸਟੀਫਨ ਸਾਲਵਾਟੋਰ',
    damonSalvatore: 'ਡੇਮਨ ਸਾਲਵਾਟੋਰ',
    bonnieBennett: 'ਬੋਨੀ ਬੇਨੇਟ',
    janeDoe: 'ਜੇਨ ਡੋ',
    bloodType: 'ਖੂਨ ਦੀ ਕਿਸਮ',
    lastVisit: 'ਆਖਰੀ ਫੇਰੀ',
    mockBloodType: 'ਓ ਪਾਜ਼ਿਟਿਵ',
    noPatientsAssigned: 'ਕੋਈ ਮਰੀਜ਼ ਨਿਰਧਾਰਤ ਨਹੀਂ ਕੀਤਾ ਗਿਆ',
    noSubjectsAssigned: 'ਤੁਹਾਡੀ ਦੇਖਭਾਲ ਲਈ ਪ੍ਰਸ਼ਾਸਨ ਦੁਆਰਾ ਵਰਤਮਾਨ ਵਿੱਚ ਕੋਈ ਮਰੀਜ਼ ਨਹੀਂ ਦਿੱਤਾ ਗਿਆ ਹੈ. ਆਪਣੀ ਸੂਚੀ ਪ੍ਰਾਪਤ ਕਰਨ ਲਈ ਸਿੰਕ੍ਰੋਨਾਈਜ਼ ਬਟਨ ਦੀ ਵਰਤੋਂ ਕਰੋ.',
    electronicHealthRecord: 'ਇਲੈਕਟ੍ਰਾਨਿਕ ਸਿਹਤ ਰਿਕਾਰਡ',
    demographics: 'ਜਨਸੰਖਿਆ ਅੰਕੜੇ',
    contactLabel: 'ਸੰਪਰਕ',
    familyGuardian: 'ਪਰਿਵਾਰਕ ਸਰਪ੍ਰਸਤ',
    biometrics: 'ਬਾਇਓਮੈਟ੍ਰਿਕਸ',
    heartRate: 'ਦਿਲ ਦੀ ਧੜਕਣ',
    bloodPressure: 'ਬਲੱਡ ਪ੍ਰੈਸ਼ਰ',
    clinicalProgressNotes: 'ਕਲੀਨਿਕਲ ਪ੍ਰਗਤੀ ਨੋਟਸ',
    formalMedicalRecords: 'ਰਸਮੀ ਮੈਡੀਕਲ ਰਿਕਾਰਡ',
    addDiagnosis: 'ਨਿਦਾਨ ਸ਼ਾਮਲ ਕਰੋ',
    collapse: 'ਸਮੇਟੋ',
    primaryImpression: 'ਪ੍ਰਾਇਮਰੀ ਪ੍ਰਭਾਵ',
    clinicalObservationDetails: 'ਕਲੀਨਿਕਲ ਨਿਰੀਖਣ ਵੇਰਵੇ',
    commitToDataRegistry: 'ਡਾਟਾ ਰਜਿਸਟਰੀ ਵਿੱਚ ਸੁਰੱਖਿਅਤ ਕਰੋ',
    assessmentRecord: 'ਮੁਲਾਂਕਣ ਰਿਕਾਰਡ',
    verifiedByMedicalStaff: 'ਮੈਡੀਕਲ ਸਟਾਫ ਦੁਆਰਾ ਪ੍ਰਮਾਣਿਤ',
    exportRecord: 'ਰਿਕਾਰਡ ਐਕਸਪੋਰਟ ਕਰੋ',
    noFormalRecords: 'ਕੋਈ ਰਸਮੀ ਕਲੀਨਿਕਲ ਰਿਕਾਰਡ ਨਹੀਂ ਮਿਲਿਆ।',
    activePrescriptions: 'ਸਰਗਰਮ ਨੁਸਖੇ',
    currentMedicationRegimen: 'ਮੌਜੂਦਾ ਦਵਾਈ ਸਕੀਮ',
    newPrescription: 'ਨਵਾਂ ਨੁਸਖਾ',
    medication: 'ਦਵਾਈ',
    dosage: 'ਖੁਰਾਕ',
    duration: 'ਅੰਤਰਾਲ',
    issuePrescription: 'ਨੁਸਖਾ ਜਾਰੀ ਕਰੋ',
    renew: 'ਰੀਨਿਊ ਕਰੋ',
    noActivePrescriptions: 'ਕੋਈ ਸਰਗਰਮ ਨੁਸਖਾ ਨਹੀਂ ਮਿਲਿਆ।',
    laboratoryResults: 'ਲੈਬ ਨਤੀਜੇ',
    recentDiagnosticMetrics: 'ਹਾਲੀਆ ਡਾਇਗਨੌਸਟਿਕ ਮੈਟ੍ਰਿਕਸ',
    newLabOrder: 'ਨਵਾਂ ਲੈਬ ਆਰਡਰ',
    testType: 'ਟੈਸਟ ਦੀ ਕਿਸਮ',
    submitOrder: 'ਆਰਡਰ ਦਰਜ ਕਰੋ',
    noLabResults: 'ਕੋਈ ਲੈਬ ਨਤੀਜੇ ਨਹੀਂ ਮਿਲੇ।',
    upcomingAppointments: 'ਆਉਣ ਵਾਲੀਆਂ ਮੁਲਾਕਾਤਾਂ',
    scheduledConsultations: 'ਨਿਰਧਾਰਤ ਸਲਾਹ-ਮਸ਼ਵਰੇ',
    noUpcomingAppointments: 'ਕੋਈ ਆਉਣ ਵਾਲੀ ਮੁਲਾਕਾਤ ਨਹੀਂ ਮਿਲੀ।',
    hypertensionStage1: 'ਹਾਈ ਬਲੱਡ ਪ੍ਰੈਸ਼ਰ ਸਟੇਜ 1',
    hypertensionNotes: 'ਸਿਸਟਮਿਕ ਮੁਲਾਂਕਣ ਲਗਾਤਾਰ ਵਧੇ ਹੋਏ ਰੀਡਿੰਗ ਦਿਖਾਉਂਦਾ ਹੈ। ਜੀਵਨ ਸ਼ੈਲੀ ਸੋਧ ਪ੍ਰੋਟੋਕੋਲ ਸ਼ੁਰੂ ਕਰਨਾ।',
    seasonalAllergies: 'ਮੌਸਮੀ ਐਲਰਜੀ',
    allergiesNotes: 'ਮਰੀਜ਼ ਬਸੰਤ ਰੁੱਤ ਦੌਰਾਨ ਲਗਾਤਾਰ ਰਾਈਨਾਈਟਿਸ ਅਤੇ ਅੱਖਾਂ ਦੀ ਖਾਰਸ਼ ਦੀ ਰਿਪੋਰਟ ਕਰਦਾ ਹੈ।',
    lisinopril: 'ਲਿਸੀਨੋਪ੍ਰਿਲ',
    loratadine: 'ਲੋરાਟਾਡੀਨ',
    thirtyDays: '30 ਦਿਨ',
    asNeeded: 'ਲੋੜ ਅਨੁਸਾਰ',
    lipidPanel: 'ਲਿਪਿਡ ਪੈਨਲ',
    metabolicScreening: 'ਮੈਟਾਬੋਲਿਕ ਸਕ੍ਰੀਨਿੰਗ',
    completedStatus: 'ਮੁਕੰਮਲ',
    orderedStatus: 'ਆਰਡਰ ਕੀਤਾ ਗਿਆ',
    cancel: 'ਰੱਦ ਕਰੋ',
    totalCholesterol: 'ਕੁੱਲ ਕੋਲੈਸਟ੍ਰੋਲ',
    abnormalStatus: 'ਅਸਧਾਰਨ',
    fastingGlucose: 'ਫਾਸਟਿੰਗ ਗਲੂਕੋਜ਼',
    followUpConsultation: 'ਫਾਲੋ-ਅਪ ਸਲਾਹ-ਮਸ਼ਵਰਾ',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const getLocale = (lang: Language): string => {
  const map: Record<Language, string> = {
    en: 'en-US',
    hi: 'hi-IN',
    bn: 'bn-IN',
    te: 'te-IN',
    mr: 'mr-IN',
    ta: 'ta-IN',
    gu: 'gu-IN',
    kn: 'kn-IN',
    ml: 'ml-IN',
    pa: 'pa-IN'
  };
  return map[lang] || 'en-US';
};

export const languagesList = languages;

export function translateName(name: string | undefined, t: (key: string) => string): string {
  if (!name) return '';
  if (name === 'Aryan Kumar') return t('aryanKumar');
  if (name === 'Elena Gilbert') return t('elenaGilbert');
  if (name === 'Stefan Salvatore') return t('stefanSalvatore');
  if (name === 'Damon Salvatore') return t('damonSalvatore');
  if (name === 'Bonnie Bennett') return t('bonnieBennett');
  if (name === 'Jane Doe') return t('janeDoe');
  return name;
}

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return (translations[language] as any)[key] || (translations['en'] as any)[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, locale: getLocale(language), setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
